import { defineRegistry } from '@videojs/compiler/shadcn';
import { skinCatalog } from '../catalog';

/** React/Tailwind publication policy for the canonical Skin inventory. */
export const skinRegistry = defineRegistry(skinCatalog, {
  name: 'videojs',
  homepage: 'https://videojs.org',
  namespace: '@videojs',
  installRoot: 'components/videojs',
  outputDir: 'canonical/registry',
  sourceRoot: 'default',
  entry: 'default-video',
  framework: 'react',
  style: 'tailwind',
  styleItem: {
    name: 'styles',
    title: 'Video.js Skin Styles',
    description: 'Shared Tailwind input, base behavior, and Default and Minimal video themes.',
  },
  utilityItem: {
    name: 'utils',
    title: 'Video.js Utilities',
    description: 'Class-name composition and state resolution utilities used by editable Video.js Skin components.',
    source: './registry/utils.ts',
    target: 'utils.ts',
    dependencies: ['clsx', 'tailwind-merge'],
  },
  items: [
    'airplay-button',
    'buffering-indicator',
    'captions-button',
    'cast-button',
    'default-video',
    'error-dialog',
    'fullscreen-button',
    'overlay',
    'pip-button',
    'play-button',
    'poster',
    'seek-button',
    'seek-indicator',
    'status-announcer',
    'status-indicator',
    'container',
    'time-slider',
    'volume-popover',
    'volume-indicator',
    'volume-slider',
  ],
});
