// AUTO-GENERATED by `@videojs/compiler`. DO NOT EDIT.
import { createComponent } from '@videojs/compiler/jsx-runtime';

export const AirPlayEnterIcon = createComponent({ name: 'AirPlayEnterIcon' });
export const AirPlayExitIcon = createComponent({ name: 'AirPlayExitIcon' });
export const CaptionsOffIcon = createComponent({ name: 'CaptionsOffIcon' });
export const CaptionsOnIcon = createComponent({ name: 'CaptionsOnIcon' });
export const CastEnterIcon = createComponent({ name: 'CastEnterIcon' });
export const CastExitIcon = createComponent({ name: 'CastExitIcon' });
export const CheckIcon = createComponent({ name: 'CheckIcon' });
export const ChevronIcon = createComponent({ name: 'ChevronIcon' });
export const FullscreenEnterIcon = createComponent({ name: 'FullscreenEnterIcon' });
export const FullscreenExitIcon = createComponent({ name: 'FullscreenExitIcon' });
export const GearIcon = createComponent({ name: 'GearIcon' });
export const PauseIcon = createComponent({ name: 'PauseIcon' });
export const PipEnterIcon = createComponent({ name: 'PipEnterIcon' });
export const PipExitIcon = createComponent({ name: 'PipExitIcon' });
export const PlayIcon = createComponent({ name: 'PlayIcon' });
export const RestartIcon = createComponent({ name: 'RestartIcon' });
export const SeekIcon = createComponent({ name: 'SeekIcon' });
export const SpeedIcon = createComponent({ name: 'SpeedIcon' });
export const SpinnerIcon = createComponent({ name: 'SpinnerIcon' });
export const SwitchesIcon = createComponent({ name: 'SwitchesIcon' });
export const VolumeHighIcon = createComponent({ name: 'VolumeHighIcon' });
export const VolumeLowIcon = createComponent({ name: 'VolumeLowIcon' });
export const VolumeOffIcon = createComponent({ name: 'VolumeOffIcon' });

export const COMPONENTS = {
  AirPlayEnterIcon: { name: 'AirPlayEnterIcon' },
  AirPlayExitIcon: { name: 'AirPlayExitIcon' },
  CaptionsOffIcon: { name: 'CaptionsOffIcon' },
  CaptionsOnIcon: { name: 'CaptionsOnIcon' },
  CastEnterIcon: { name: 'CastEnterIcon' },
  CastExitIcon: { name: 'CastExitIcon' },
  CheckIcon: { name: 'CheckIcon' },
  ChevronIcon: { name: 'ChevronIcon' },
  FullscreenEnterIcon: { name: 'FullscreenEnterIcon' },
  FullscreenExitIcon: { name: 'FullscreenExitIcon' },
  GearIcon: { name: 'GearIcon' },
  PauseIcon: { name: 'PauseIcon' },
  PipEnterIcon: { name: 'PipEnterIcon' },
  PipExitIcon: { name: 'PipExitIcon' },
  PlayIcon: { name: 'PlayIcon' },
  RestartIcon: { name: 'RestartIcon' },
  SeekIcon: { name: 'SeekIcon' },
  SpeedIcon: { name: 'SpeedIcon' },
  SpinnerIcon: { name: 'SpinnerIcon' },
  SwitchesIcon: { name: 'SwitchesIcon' },
  VolumeHighIcon: { name: 'VolumeHighIcon' },
  VolumeLowIcon: { name: 'VolumeLowIcon' },
  VolumeOffIcon: { name: 'VolumeOffIcon' },
} as const;

export type Components = typeof COMPONENTS;
