// Generated by `vjsc generate`.
import { defineTarget } from 'vjsc/components';

export const AirPlayButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'AirPlayButton',
  },
  props: {
    from: '@videojs/react',
    name: 'AirPlayButton',
    path: ['Props'],
  },
});

export const AudioTrackRadioGroup = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'AudioTrackRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'AudioTrackRadioGroup',
    path: ['Props'],
  },
});

export const BufferingIndicator = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'BufferingIndicator',
  },
  props: {
    from: '@videojs/react',
    name: 'BufferingIndicator',
    path: ['Props'],
  },
});

export const CaptionsButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'CaptionsButton',
  },
  props: {
    from: '@videojs/react',
    name: 'CaptionsButton',
    path: ['Props'],
  },
});

export const CaptionsRadioGroup = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'CaptionsRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'CaptionsRadioGroup',
    path: ['Props'],
  },
});

export const CastButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'CastButton',
  },
  props: {
    from: '@videojs/react',
    name: 'CastButton',
    path: ['Props'],
  },
});

export const Container = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'Container',
  },
  props: {
    from: '@videojs/react',
    name: 'Container',
    path: ['Props'],
  },
});

export const Controls = {
  Group: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['GroupProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['RootProps'],
    },
  }),
} as const;

export const ErrorDialog = {
  Close: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Close'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['CloseProps'],
    },
  }),
  Description: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Description'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['DescriptionProps'],
    },
  }),
  Popup: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['PopupProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['RootProps'],
    },
  }),
  Title: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Title'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['TitleProps'],
    },
  }),
} as const;

export const FullscreenButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'FullscreenButton',
  },
  props: {
    from: '@videojs/react',
    name: 'FullscreenButton',
    path: ['Props'],
  },
});

export const Gesture = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'Gesture',
  },
  props: {
    from: '@videojs/react',
    name: 'Gesture',
    path: ['Props'],
  },
});

export const Hotkey = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'Hotkey',
  },
  props: {
    from: '@videojs/react',
    name: 'Hotkey',
    path: ['Props'],
  },
});

export const Menu = {
  CheckboxItem: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['CheckboxItem'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['CheckboxItemProps'],
    },
  }),
  Content: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Content'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ContentProps'],
    },
  }),
  Group: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupProps'],
    },
  }),
  GroupLabel: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupLabel'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupLabelProps'],
    },
  }),
  Item: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Item'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemProps'],
    },
  }),
  ItemIndicator: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemIndicator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemIndicatorProps'],
    },
  }),
  RadioGroup: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioGroup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioGroupProps'],
    },
  }),
  RadioItem: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioItem'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioItemProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RootProps'],
    },
  }),
  Separator: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Separator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['SeparatorProps'],
    },
  }),
  SubmenuTrigger: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['TriggerProps'],
    },
  }),
  Trigger: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['TriggerProps'],
    },
  }),
} as const;

export const MuteButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'MuteButton',
  },
  props: {
    from: '@videojs/react',
    name: 'MuteButton',
    path: ['Props'],
  },
});

export const PiPButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'PiPButton',
  },
  props: {
    from: '@videojs/react',
    name: 'PiPButton',
    path: ['Props'],
  },
});

export const PlaybackRateRadioGroup = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'PlaybackRateRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'PlaybackRateRadioGroup',
    path: ['Props'],
  },
});

export const PlayButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'PlayButton',
  },
  props: {
    from: '@videojs/react',
    name: 'PlayButton',
    path: ['Props'],
  },
});

export const Popover = {
  Arrow: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Arrow'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['ArrowProps'],
    },
  }),
  Popup: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['PopupProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['RootProps'],
    },
  }),
  Trigger: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['TriggerProps'],
    },
  }),
} as const;

export const Poster = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'Poster',
  },
  props: {
    from: '@videojs/react',
    name: 'Poster',
    path: ['Props'],
  },
});

export const QualityRadioGroup = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'QualityRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'QualityRadioGroup',
    path: ['Props'],
  },
});

export const SeekButton = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'SeekButton',
  },
  props: {
    from: '@videojs/react',
    name: 'SeekButton',
    path: ['Props'],
  },
});

export const SeekIndicator = {
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['RootProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['ValueProps'],
    },
  }),
} as const;

export const Slider = {
  Buffer: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Buffer'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['BufferProps'],
    },
  }),
  Fill: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['FillProps'],
    },
  }),
  Preview: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['PreviewProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['RootProps'],
    },
  }),
  Thumb: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['ThumbProps'],
    },
  }),
  Thumbnail: {
    Image: defineTarget({
      import: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'Image'],
      },
      props: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'ImageProps'],
      },
    }),
    Root: defineTarget({
      import: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'Root'],
      },
      props: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'RootProps'],
      },
    }),
  } as const,
  Track: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['TrackProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['ValueProps'],
    },
  }),
} as const;

export const StatusAnnouncer = defineTarget({
  import: {
    from: '@videojs/react',
    name: 'StatusAnnouncer',
  },
  props: {
    from: '@videojs/react',
    name: 'StatusAnnouncer',
    path: ['Props'],
  },
});

export const StatusIndicator = {
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['RootProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['ValueProps'],
    },
  }),
} as const;

export const Time = {
  Group: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['GroupProps'],
    },
  }),
  Separator: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Separator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['SeparatorProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['ValueProps'],
    },
  }),
} as const;

export const TimeSlider = {
  Buffer: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Buffer'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['BufferProps'],
    },
  }),
  Chapters: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Chapters'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChaptersProps'],
    },
  }),
  ChapterTitle: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChapterTitle'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChapterTitleProps'],
    },
  }),
  Fill: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['FillProps'],
    },
  }),
  Preview: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['PreviewProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['RootProps'],
    },
  }),
  Thumb: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ThumbProps'],
    },
  }),
  Track: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['TrackProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ValueProps'],
    },
  }),
} as const;

export const Tooltip = {
  Arrow: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Arrow'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ArrowProps'],
    },
  }),
  Label: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Label'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['LabelProps'],
    },
  }),
  Popup: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['PopupProps'],
    },
  }),
  Provider: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Provider'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ProviderProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['RootProps'],
    },
  }),
  Shortcut: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Shortcut'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ShortcutProps'],
    },
  }),
  Trigger: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['TriggerProps'],
    },
  }),
} as const;

export const VolumeIndicator = {
  Fill: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['FillProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['RootProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['ValueProps'],
    },
  }),
} as const;

export const VolumeSlider = {
  Fill: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['FillProps'],
    },
  }),
  Preview: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['PreviewProps'],
    },
  }),
  Root: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['RootProps'],
    },
  }),
  Thumb: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['ThumbProps'],
    },
  }),
  Track: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['TrackProps'],
    },
  }),
  Value: defineTarget({
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['ValueProps'],
    },
  }),
} as const;

export const targets = {
  AirPlayButton,
  AudioTrackRadioGroup,
  BufferingIndicator,
  CaptionsButton,
  CaptionsRadioGroup,
  CastButton,
  Container,
  Controls,
  ErrorDialog,
  FullscreenButton,
  Gesture,
  Hotkey,
  Menu,
  MuteButton,
  PiPButton,
  PlaybackRateRadioGroup,
  PlayButton,
  Popover,
  Poster,
  QualityRadioGroup,
  SeekButton,
  SeekIndicator,
  Slider,
  StatusAnnouncer,
  StatusIndicator,
  Time,
  TimeSlider,
  Tooltip,
  VolumeIndicator,
  VolumeSlider,
} as const;
