// Generated by `vjsc generate`.
export const AirPlayButton = {
  import: {
    from: '@videojs/react',
    name: 'AirPlayButton',
  },
  props: {
    from: '@videojs/react',
    name: 'AirPlayButton',
    path: ['Props'],
  },
} as const;

export const AudioTrackRadioGroup = {
  import: {
    from: '@videojs/react',
    name: 'AudioTrackRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'AudioTrackRadioGroup',
    path: ['Props'],
  },
} as const;

export const BufferingIndicator = {
  import: {
    from: '@videojs/react',
    name: 'BufferingIndicator',
  },
  props: {
    from: '@videojs/react',
    name: 'BufferingIndicator',
    path: ['Props'],
  },
} as const;

export const CaptionsButton = {
  import: {
    from: '@videojs/react',
    name: 'CaptionsButton',
  },
  props: {
    from: '@videojs/react',
    name: 'CaptionsButton',
    path: ['Props'],
  },
} as const;

export const CaptionsRadioGroup = {
  import: {
    from: '@videojs/react',
    name: 'CaptionsRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'CaptionsRadioGroup',
    path: ['Props'],
  },
} as const;

export const CastButton = {
  import: {
    from: '@videojs/react',
    name: 'CastButton',
  },
  props: {
    from: '@videojs/react',
    name: 'CastButton',
    path: ['Props'],
  },
} as const;

export const Container = {
  import: {
    from: '@videojs/react',
    name: 'Container',
  },
  props: {
    from: '@videojs/react',
    name: 'Container',
    path: ['Props'],
  },
} as const;

export const Controls = {
  Group: {
    import: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['GroupProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Controls',
      path: ['RootProps'],
    },
  },
} as const;

export const ErrorDialog = {
  Close: {
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Close'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['CloseProps'],
    },
  },
  Description: {
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Description'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['DescriptionProps'],
    },
  },
  Popup: {
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['PopupProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['RootProps'],
    },
  },
  Title: {
    import: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['Title'],
    },
    props: {
      from: '@videojs/react',
      name: 'ErrorDialog',
      path: ['TitleProps'],
    },
  },
} as const;

export const FullscreenButton = {
  import: {
    from: '@videojs/react',
    name: 'FullscreenButton',
  },
  props: {
    from: '@videojs/react',
    name: 'FullscreenButton',
    path: ['Props'],
  },
} as const;

export const Gesture = {
  import: {
    from: '@videojs/react',
    name: 'Gesture',
  },
  props: {
    from: '@videojs/react',
    name: 'Gesture',
    path: ['Props'],
  },
} as const;

export const Hotkey = {
  import: {
    from: '@videojs/react',
    name: 'Hotkey',
  },
  props: {
    from: '@videojs/react',
    name: 'Hotkey',
    path: ['Props'],
  },
} as const;

export const Menu = {
  CheckboxItem: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['CheckboxItem'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['CheckboxItemProps'],
    },
  },
  Content: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Content'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ContentProps'],
    },
  },
  Group: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupProps'],
    },
  },
  GroupLabel: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupLabel'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['GroupLabelProps'],
    },
  },
  Item: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Item'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemProps'],
    },
  },
  ItemIndicator: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemIndicator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['ItemIndicatorProps'],
    },
  },
  RadioGroup: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioGroup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioGroupProps'],
    },
  },
  RadioItem: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioItem'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RadioItemProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['RootProps'],
    },
  },
  Separator: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Separator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['SeparatorProps'],
    },
  },
  SubmenuTrigger: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['TriggerProps'],
    },
  },
  Trigger: {
    import: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Menu',
      path: ['TriggerProps'],
    },
  },
} as const;

export const MuteButton = {
  import: {
    from: '@videojs/react',
    name: 'MuteButton',
  },
  props: {
    from: '@videojs/react',
    name: 'MuteButton',
    path: ['Props'],
  },
} as const;

export const PiPButton = {
  import: {
    from: '@videojs/react',
    name: 'PiPButton',
  },
  props: {
    from: '@videojs/react',
    name: 'PiPButton',
    path: ['Props'],
  },
} as const;

export const PlaybackRateRadioGroup = {
  import: {
    from: '@videojs/react',
    name: 'PlaybackRateRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'PlaybackRateRadioGroup',
    path: ['Props'],
  },
} as const;

export const PlayButton = {
  import: {
    from: '@videojs/react',
    name: 'PlayButton',
  },
  props: {
    from: '@videojs/react',
    name: 'PlayButton',
    path: ['Props'],
  },
} as const;

export const Popover = {
  Arrow: {
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Arrow'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['ArrowProps'],
    },
  },
  Popup: {
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['PopupProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['RootProps'],
    },
  },
  Trigger: {
    import: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Popover',
      path: ['TriggerProps'],
    },
  },
} as const;

export const Poster = {
  import: {
    from: '@videojs/react',
    name: 'Poster',
  },
  props: {
    from: '@videojs/react',
    name: 'Poster',
    path: ['Props'],
  },
} as const;

export const QualityRadioGroup = {
  import: {
    from: '@videojs/react',
    name: 'QualityRadioGroup',
  },
  props: {
    from: '@videojs/react',
    name: 'QualityRadioGroup',
    path: ['Props'],
  },
} as const;

export const SeekButton = {
  import: {
    from: '@videojs/react',
    name: 'SeekButton',
  },
  props: {
    from: '@videojs/react',
    name: 'SeekButton',
    path: ['Props'],
  },
} as const;

export const SeekIndicator = {
  Root: {
    import: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['RootProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'SeekIndicator',
      path: ['ValueProps'],
    },
  },
} as const;

export const Slider = {
  Buffer: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Buffer'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['BufferProps'],
    },
  },
  Fill: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['FillProps'],
    },
  },
  Preview: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['PreviewProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['RootProps'],
    },
  },
  Thumb: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['ThumbProps'],
    },
  },
  Thumbnail: {
    Image: {
      import: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'Image'],
      },
      props: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'ImageProps'],
      },
    },
    Root: {
      import: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'Root'],
      },
      props: {
        from: '@videojs/react',
        name: 'Slider',
        path: ['Thumbnail', 'RootProps'],
      },
    },
  },
  Track: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['TrackProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'Slider',
      path: ['ValueProps'],
    },
  },
} as const;

export const StatusAnnouncer = {
  import: {
    from: '@videojs/react',
    name: 'StatusAnnouncer',
  },
  props: {
    from: '@videojs/react',
    name: 'StatusAnnouncer',
    path: ['Props'],
  },
} as const;

export const StatusIndicator = {
  Root: {
    import: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['RootProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'StatusIndicator',
      path: ['ValueProps'],
    },
  },
} as const;

export const Time = {
  Group: {
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Group'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['GroupProps'],
    },
  },
  Separator: {
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Separator'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['SeparatorProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'Time',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'Time',
      path: ['ValueProps'],
    },
  },
} as const;

export const TimeSlider = {
  Buffer: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Buffer'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['BufferProps'],
    },
  },
  Chapters: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Chapters'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChaptersProps'],
    },
  },
  ChapterTitle: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChapterTitle'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ChapterTitleProps'],
    },
  },
  Fill: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['FillProps'],
    },
  },
  Preview: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['PreviewProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['RootProps'],
    },
  },
  Thumb: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ThumbProps'],
    },
  },
  Track: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['TrackProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'TimeSlider',
      path: ['ValueProps'],
    },
  },
} as const;

export const Tooltip = {
  Arrow: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Arrow'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ArrowProps'],
    },
  },
  Label: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Label'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['LabelProps'],
    },
  },
  Popup: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Popup'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['PopupProps'],
    },
  },
  Provider: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Provider'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ProviderProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['RootProps'],
    },
  },
  Shortcut: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Shortcut'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['ShortcutProps'],
    },
  },
  Trigger: {
    import: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['Trigger'],
    },
    props: {
      from: '@videojs/react',
      name: 'Tooltip',
      path: ['TriggerProps'],
    },
  },
} as const;

export const VolumeIndicator = {
  Fill: {
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['FillProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['RootProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeIndicator',
      path: ['ValueProps'],
    },
  },
} as const;

export const VolumeSlider = {
  Fill: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Fill'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['FillProps'],
    },
  },
  Preview: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Preview'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['PreviewProps'],
    },
  },
  Root: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Root'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['RootProps'],
    },
  },
  Thumb: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Thumb'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['ThumbProps'],
    },
  },
  Track: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Track'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['TrackProps'],
    },
  },
  Value: {
    import: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['Value'],
    },
    props: {
      from: '@videojs/react',
      name: 'VolumeSlider',
      path: ['ValueProps'],
    },
  },
} as const;

export const entries = {
  AirPlayButton,
  AudioTrackRadioGroup,
  BufferingIndicator,
  CaptionsButton,
  CaptionsRadioGroup,
  CastButton,
  Container,
  Controls,
  ErrorDialog,
  FullscreenButton,
  Gesture,
  Hotkey,
  Menu,
  MuteButton,
  PiPButton,
  PlaybackRateRadioGroup,
  PlayButton,
  Popover,
  Poster,
  QualityRadioGroup,
  SeekButton,
  SeekIndicator,
  Slider,
  StatusAnnouncer,
  StatusIndicator,
  Time,
  TimeSlider,
  Tooltip,
  VolumeIndicator,
  VolumeSlider,
} as const;
