import { dirname, posix } from 'node:path';

import { absolutePath, toPosixPath } from '../../utils/path';
import { type ComponentSchema, defineSchema } from '../definition';
import { type ComponentInput, discoverSchema, type DefinedSchemaComponent, type SchemaComponent } from './discover';

export type { ComponentFileSet, ComponentInput } from './discover';

export interface ComponentSchemaOptions {
  /** Base directory used to resolve relative paths. */
  readonly cwd?: string | undefined;
  /** Module specifier source files use to import the generated components. */
  readonly source: string;
  readonly include: readonly ComponentInput[];
  readonly exclude?: string | readonly string[] | undefined;
  readonly output: string;
}

export interface ComponentSchemaOutput {
  readonly code: string;
  readonly declaration: string;
  readonly schema: ComponentSchema;
  readonly watchFiles: readonly string[];
}

export interface RenderComponentSchemaOptions {
  /** Module specifier source files use to import the generated components. */
  readonly source: string;
  /** Components the schema declares by name alone, such as icons generated from assets rather than source modules. */
  readonly components: readonly string[];
  /** Emit JavaScript for a module written straight to disk, or TypeScript for a module a bundler compiles. */
  readonly language?: 'js' | 'ts' | undefined;
}

/** Render a schema module and its declarations for components that have no definition module of their own. */
export function renderComponentSchema(
  options: RenderComponentSchemaOptions
): Pick<ComponentSchemaOutput, 'code' | 'declaration'> {
  const entries = [...new Set(options.components)]
    .sort((a, b) => a.localeCompare(b))
    .map((name): SchemaComponent => ({ kind: 'file', fileName: '', name, definition: { name } }));
  if (entries.length === 0) throw new Error(`Component schema \`${options.source}\` declares no components.`);

  const language = options.language ?? 'ts';

  return {
    code: `${[
      emitHeader(entries, '', language),
      emitDefinitions(entries, language),
      emitComponents(entries, language),
      emitSchema(options.source, language),
    ].join('\n\n')}\n`,
    declaration: `${[
      emitDeclarationHeader(entries, ''),
      emitDeclarationDefinitions(entries),
      emitDeclarationComponents(entries),
      emitDeclarationSchema(options.source),
    ].join('\n\n')}\n`,
  };
}

/** Produce a component schema module without writing it to disk. */
export function createComponentSchema(options: ComponentSchemaOptions): ComponentSchemaOutput {
  const { cwd = process.cwd(), exclude, include, output, source } = options;

  const outputAbsolute = absolutePath(cwd, output);
  const discovered = discoverSchema({ cwd, include, ...(exclude ? { exclude } : {}) });

  const entries = [...discovered.components].sort((a, b) => a.name.localeCompare(b.name));
  if (entries.length === 0) throw new Error(`No component sources matched: ${JSON.stringify(include)}`);

  const duplicate = entries.find((entry, index) => entry.name === entries[index - 1]?.name);
  if (duplicate) throw new Error(`Duplicate component name: ${duplicate.name}`);

  const code = `${[
    emitHeader(entries, outputAbsolute),
    emitDefinitions(entries),
    emitComponents(entries),
    emitSchema(source),
  ].join('\n\n')}\n`;

  return {
    code,
    declaration: `${[
      emitDeclarationHeader(entries, outputAbsolute),
      emitDeclarationDefinitions(entries),
      emitDeclarationComponents(entries),
      emitDeclarationSchema(source),
    ].join('\n\n')}\n`,
    schema: defineSchema(source, Object.fromEntries(entries.map((entry) => [entry.name, entry.definition]))),
    watchFiles: discovered.watchFiles,
  };
}

function compareImportSpecifiers(a: string, b: string): number {
  return a.replaceAll('/', ' ').localeCompare(b.replaceAll('/', ' '));
}

function emitHeader(entries: readonly SchemaComponent[], outputFile: string, language: 'js' | 'ts' = 'ts'): string {
  const definitionLines = entries
    .filter((entry): entry is DefinedSchemaComponent => entry.kind === 'definition')
    .sort((a, b) => compareImportSpecifiers(definitionFrom(a, outputFile), definitionFrom(b, outputFile)))
    .map((entry) => `import ${entry.name}Def from '${definitionFrom(entry, outputFile)}';`)
    .join('\n');
  const imports =
    language === 'ts'
      ? `${nameOnlyTypes(entries)}type ComponentSchema, type ComponentFrom, createComponent, defineSchema`
      : 'createComponent, defineSchema';
  const header = `// Generated by VJSC.\nimport { ${imports} } from 'vjsc/components';`;

  return definitionLines ? `${header}\n\n${definitionLines}` : header;
}

/** Name-only components are typed as prop-less definitions, which the header must import. */
function nameOnlyTypes(entries: readonly SchemaComponent[]): string {
  return entries.some((entry) => entry.kind !== 'definition') ? 'type ComponentDefinition, type EmptyProps, ' : '';
}

function definitionType(entry: SchemaComponent): string {
  return entry.kind === 'definition'
    ? `typeof ${entry.name}Def`
    : `ComponentDefinition<EmptyProps> & { readonly name: '${entry.name}' }`;
}

function definitionFrom(entry: DefinedSchemaComponent, outputFile: string): string {
  const path = posix.relative(
    toPosixPath(dirname(outputFile)),
    toPosixPath(entry.fileName).replace(/\.(?:[cm]?[jt]s|[jt]sx)$/, '')
  );

  return path.startsWith('.') ? path : `./${path}`;
}

function definitionRef(entry: SchemaComponent): string {
  return entry.kind === 'definition' ? `${entry.name}Def` : `{ name: '${entry.name}' }`;
}

function emitDefinitions(entries: readonly SchemaComponent[], language: 'js' | 'ts' = 'ts'): string {
  const lines = entries.map((entry) => `  ${entry.name}: ${definitionRef(entry)},`);

  if (language === 'js') return `const DEFINITIONS = {\n${lines.join('\n')}\n};`;

  const typeLines = entries.map((entry) => `  readonly ${entry.name}: ${definitionType(entry)};`);

  return `const DEFINITIONS: {\n${typeLines.join('\n')}\n} = {\n${lines.join('\n')}\n};`;
}

function emitComponents(entries: readonly SchemaComponent[], language: 'js' | 'ts' = 'ts'): string {
  return entries
    .map((entry) =>
      language === 'js'
        ? `export const ${entry.name} = createComponent(DEFINITIONS.${entry.name});`
        : `export const ${entry.name}: ComponentFrom<(typeof DEFINITIONS)['${entry.name}']> = createComponent(DEFINITIONS.${entry.name});`
    )
    .join('\n');
}

function emitSchema(source: string, language: 'js' | 'ts' = 'ts'): string {
  const sourceLiteral = JSON.stringify(source);
  const type = language === 'ts' ? `: ComponentSchema<typeof DEFINITIONS, ${sourceLiteral}>` : '';

  return `const schema${type} = defineSchema(${sourceLiteral}, DEFINITIONS);

export default schema;`;
}

function emitDeclarationHeader(entries: readonly SchemaComponent[], outputFile: string): string {
  const definitionLines = entries
    .filter((entry): entry is DefinedSchemaComponent => entry.kind === 'definition')
    .sort((a, b) => compareImportSpecifiers(definitionFrom(a, outputFile), definitionFrom(b, outputFile)))
    .map((entry) => `import ${entry.name}Def from '${definitionFrom(entry, outputFile)}';`)
    .join('\n');
  const header = `import { ${nameOnlyTypes(entries)}type ComponentSchema, type ComponentFrom } from 'vjsc/components';`;

  return definitionLines ? `${header}\n\n${definitionLines}` : header;
}

function emitDeclarationDefinitions(entries: readonly SchemaComponent[]): string {
  const lines = entries.map((entry) => `  readonly ${entry.name}: ${definitionType(entry)};`);

  return `declare const DEFINITIONS: {\n${lines.join('\n')}\n};`;
}

function emitDeclarationComponents(entries: readonly SchemaComponent[]): string {
  return entries
    .map((entry) => `export declare const ${entry.name}: ComponentFrom<(typeof DEFINITIONS)['${entry.name}']>;`)
    .join('\n');
}

function emitDeclarationSchema(source: string): string {
  return `declare const schema: ComponentSchema<typeof DEFINITIONS, ${JSON.stringify(source)}>;\n\nexport default schema;`;
}
