import { dirname, posix } from 'node:path';

import { absolutePath, toPosixPath } from '../../utils/path';
import { type ComponentSchema, defineSchema } from '../definition';
import { type ComponentSource, discoverSchema, type ManifestSchemaComponent, type SchemaComponent } from './discover';

export type { ComponentFileSet, ComponentSource } from './discover';

export interface CreateSchemaModuleOptions {
  /** Base directory used to resolve relative paths. */
  readonly cwd?: string | undefined;
  /** Module specifier source files use to import the generated components. */
  readonly source: string;
  readonly include: readonly ComponentSource[];
  readonly exclude?: string | readonly string[] | undefined;
  readonly output: string;
}

export interface SchemaModule {
  readonly code: string;
  readonly declaration: string;
  readonly schema: ComponentSchema;
  readonly watchFiles: readonly string[];
}

/** Produce a component schema module without writing it to disk. */
export function createSchemaModule(options: CreateSchemaModuleOptions): SchemaModule {
  const { cwd = process.cwd(), exclude, include, output, source } = options;

  const outputAbsolute = absolutePath(cwd, output);
  const discovered = discoverSchema({ cwd, include, ...(exclude ? { exclude } : {}) });

  const entries = [...discovered.components].sort((a, b) => a.name.localeCompare(b.name));
  if (entries.length === 0) throw new Error(`No component sources matched: ${JSON.stringify(include)}`);

  const duplicate = entries.find((entry, index) => entry.name === entries[index - 1]?.name);
  if (duplicate) throw new Error(`Duplicate component name: ${duplicate.name}`);

  const code = `${[
    emitHeader(entries, outputAbsolute),
    emitDefinitions(entries),
    emitComponents(entries),
    emitSchema(source),
  ].join('\n\n')}\n`;

  return {
    code,
    declaration: `${[
      emitDeclarationHeader(entries, outputAbsolute),
      emitDeclarationDefinitions(entries),
      emitDeclarationComponents(entries),
      emitDeclarationSchema(source),
    ].join('\n\n')}\n`,
    schema: defineSchema(source, Object.fromEntries(entries.map((entry) => [entry.name, entry.definition]))),
    watchFiles: discovered.watchFiles,
  };
}

function compareImportSpecifiers(a: string, b: string): number {
  return a.replaceAll('/', ' ').localeCompare(b.replaceAll('/', ' '));
}

function emitHeader(entries: readonly SchemaComponent[], outputFile: string): string {
  const manifestLines = entries
    .filter((entry): entry is ManifestSchemaComponent => entry.kind === 'manifest')
    .sort((a, b) => compareImportSpecifiers(manifestFrom(a, outputFile), manifestFrom(b, outputFile)))
    .map((entry) => `import ${entry.name}Def from '${manifestFrom(entry, outputFile)}';`)
    .join('\n');

  const header = `// Generated by the VJSC bundler plugin.
import { type ComponentSchema, type CreateComponentResult, createComponent, defineSchema } from 'vjsc/components';`;

  return manifestLines ? `${header}\n\n${manifestLines}` : header;
}

function manifestFrom(entry: ManifestSchemaComponent, outputFile: string): string {
  const path = posix.relative(
    toPosixPath(dirname(outputFile)),
    toPosixPath(entry.fileName).replace(/\.(?:[cm]?[jt]s|[jt]sx)$/, '')
  );

  return path.startsWith('.') ? path : `./${path}`;
}

function manifestRef(entry: SchemaComponent): string {
  return entry.kind === 'manifest' ? `${entry.name}Def` : `{ name: '${entry.name}' }`;
}

function emitDefinitions(entries: readonly SchemaComponent[]): string {
  const typeLines = entries.map((entry) => {
    const type = entry.kind === 'manifest' ? `typeof ${entry.name}Def` : `{ readonly name: '${entry.name}' }`;

    return `  readonly ${entry.name}: ${type};`;
  });
  const lines = entries.map((entry) => `  ${entry.name}: ${manifestRef(entry)},`);

  return `const DEFINITIONS: {\n${typeLines.join('\n')}\n} = {\n${lines.join('\n')}\n};`;
}

function emitComponents(entries: readonly SchemaComponent[]): string {
  return entries
    .map(
      (entry) =>
        `export const ${entry.name}: CreateComponentResult<(typeof DEFINITIONS)['${entry.name}']> = createComponent(DEFINITIONS.${entry.name});`
    )
    .join('\n');
}

function emitSchema(source: string): string {
  const sourceLiteral = JSON.stringify(source);

  return `const schema: ComponentSchema<typeof DEFINITIONS, ${sourceLiteral}> = defineSchema(${sourceLiteral}, DEFINITIONS);

export default schema;`;
}

function emitDeclarationHeader(entries: readonly SchemaComponent[], outputFile: string): string {
  const manifestLines = entries
    .filter((entry): entry is ManifestSchemaComponent => entry.kind === 'manifest')
    .sort((a, b) => compareImportSpecifiers(manifestFrom(a, outputFile), manifestFrom(b, outputFile)))
    .map((entry) => `import ${entry.name}Def from '${manifestFrom(entry, outputFile)}';`)
    .join('\n');
  const header = `import { type ComponentSchema, type CreateComponentResult } from 'vjsc/components';`;

  return manifestLines ? `${header}\n\n${manifestLines}` : header;
}

function emitDeclarationDefinitions(entries: readonly SchemaComponent[]): string {
  const lines = entries.map((entry) => {
    const type = entry.kind === 'manifest' ? `typeof ${entry.name}Def` : `{ readonly name: '${entry.name}' }`;

    return `  readonly ${entry.name}: ${type};`;
  });

  return `declare const DEFINITIONS: {\n${lines.join('\n')}\n};`;
}

function emitDeclarationComponents(entries: readonly SchemaComponent[]): string {
  return entries
    .map((entry) => `export declare const ${entry.name}: CreateComponentResult<(typeof DEFINITIONS)['${entry.name}']>;`)
    .join('\n');
}

function emitDeclarationSchema(source: string): string {
  return `declare const schema: ComponentSchema<typeof DEFINITIONS, ${JSON.stringify(source)}>;\n\nexport default schema;`;
}
