import { existsSync, globSync } from 'node:fs';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';

import { isString } from '@videojs/utils/predicate';

import { isStyleModulePath } from './modules';
import type { ResolvedStyleRule, ResolvedStyles } from './resolved';

/** Import specifier Tailwind entries use for the generated candidate manifest. */
export const CANDIDATES_ALIAS = 'vjsc:candidates';

export interface CandidateManifestOptions {
  /** Manifest path relative to the project root. Defaults to the Vite cache directory. */
  readonly path?: string | undefined;
  /**
   * Style modules recorded when the build starts, as globs relative to the project root or absolute. Tailwind compiles
   * its entry without waiting for component transforms, so a cold build only sees every utility when the modules that
   * declare them are recorded up front.
   */
  readonly include?: string | readonly string[] | undefined;
}

export interface CandidateManifest {
  readonly path: string;
  /** Create the manifest when it does not exist so Tailwind entries can import it before any module resolves. */
  ensure(): Promise<void>;
  /** Merge the rules of some style modules and rewrite the manifest when its candidates change. */
  record(styles: Pick<ResolvedStyles, 'modules'>): Promise<void>;
}

export interface CandidateManifestWriteOptions {
  /**
   * Carry candidates over from a manifest an earlier session wrote, so a restart never shrinks it before modules record
   * again. Unneeded when every style module is recorded up front.
   */
  readonly persist?: boolean | undefined;
}

/** Normalize the `candidates` plugin option; `undefined` disables the manifest. */
export function candidateManifestOptions(
  candidates: string | boolean | CandidateManifestOptions | undefined
): CandidateManifestOptions | undefined {
  if (candidates === true) return {};

  return isString(candidates) ? { path: candidates } : candidates || undefined;
}

/** The style modules a manifest's `include` globs match, as sorted absolute paths. */
export function discoverStyleModules(root: string, include: string | readonly string[]): string[] {
  const patterns = isString(include) ? [include] : include;
  const files = patterns.flatMap((pattern) =>
    isAbsolute(pattern) ? globSync(pattern) : globSync(pattern, { cwd: root }).map((file) => resolve(root, file))
  );

  return [...new Set(files.filter(isStyleModulePath))].sort();
}

/**
 * Render every utility of the given rules, including variant utilities, as Tailwind `@source inline()` entries. Extra
 * candidates carry over entries from an earlier session so a restart never shrinks the manifest.
 */
export function renderCandidateManifest(rules: Iterable<ResolvedStyleRule>, extra: Iterable<string> = []): string {
  const candidates = new Set<string>(extra);

  for (const rule of rules) {
    for (const utility of rule.utilities) candidates.add(utility);

    for (const utilities of Object.values(rule.variants)) {
      for (const utility of utilities) candidates.add(utility);
    }
  }

  const lines = [...candidates].sort().map((candidate) => `@source inline(${JSON.stringify(candidate)});`);

  return ['/* Generated by vjsc. Style module utilities for Tailwind source scanning. */', ...lines, ''].join('\n');
}

/** Read the candidates an existing manifest lists. */
export function parseCandidateManifest(content: string): string[] {
  return [...content.matchAll(/^@source inline\(("(?:[^"\\]|\\.)*")\);$/gm)].map(([, json]) => JSON.parse(json!));
}

/** Default manifest location: the Vite cache directory of the package that owns `root`. */
export function resolveCandidateManifestPath(root: string, cacheDir?: string): string {
  const cache = cacheDir ? resolve(root, cacheDir) : resolve(packageRoot(root), 'node_modules/.vite');

  return resolve(cache, 'vjsc/candidates.css');
}

export function createCandidateManifest(path: string, options: CandidateManifestWriteOptions = {}): CandidateManifest {
  const persist = options.persist ?? true;
  const rulesByModule = new Map<string, ReadonlyMap<string, ResolvedStyleRule>>();
  const persisted = new Set<string>();
  let written: string | undefined;
  let queue = Promise.resolve();

  // Modules compile in parallel, so writes queue up and land through a rename: two overlapping writes would interleave
  // their bytes, and Tailwind must never read a half-written manifest.
  const write = (content: string): Promise<void> => {
    queue = queue.then(async () => {
      if (content === written) return;

      const staging = `${path}.${process.pid}.tmp`;

      await mkdir(dirname(path), { recursive: true });
      await writeFile(staging, content);
      await rename(staging, path);
      written = content;
    });

    return queue;
  };

  return {
    path,
    async ensure() {
      if (written !== undefined) return;

      written = await readFile(path, 'utf8').catch(() => undefined);

      if (written === undefined) await write(renderCandidateManifest([]));
      else if (persist) for (const candidate of parseCandidateManifest(written)) persisted.add(candidate);
    },
    async record(styles) {
      let changed = written === undefined;

      for (const [modulePath, rules] of styles.modules) {
        if (rulesByModule.get(modulePath) === rules) continue;

        rulesByModule.set(modulePath, rules);
        changed = true;
      }

      if (!changed) return;

      const rules = [...rulesByModule.values()].flatMap((moduleRules) => [...moduleRules.values()]);

      await write(renderCandidateManifest(rules, persisted));
    },
  };
}

function packageRoot(root: string): string {
  let directory = resolve(root);

  while (!existsSync(resolve(directory, 'package.json'))) {
    const parent = dirname(directory);
    if (parent === directory) return resolve(root);

    directory = parent;
  }

  return directory;
}
