import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

import { isString } from '@videojs/utils/predicate';

/**
 * Pure helpers behind `generate-html-entries.ts`: derive the `video.js` re-export tree and package manifest from
 * `@videojs/html`'s manifest and source tree, so the two can never drift apart by hand.
 */

export type ExportTarget = string | Record<string, string>;

export type ExportsMap = Record<string, ExportTarget>;

export interface HtmlPackageJson {
  main: string;
  module: string;
  types: string;
  sideEffects: string[];
  exports: ExportsMap;
  peerDependencies?: Record<string, string>;
  peerDependenciesMeta?: Record<string, { optional?: boolean }>;
}

export interface HtmlModule {
  /** Path inside `dist/<mode>/` without extension, e.g. `define/video/player`. Mirrors the `@videojs/html` layout. */
  modulePath: string;
  /** The public `@videojs/html/…` specifier that reaches the module. */
  specifier: string;
  /** Whether the source exports anything. Side-effect-only modules (custom element registration) are imported instead. */
  hasExports: boolean;
  /** Whether the source has a default export, which `export *` does not forward. */
  hasDefault: boolean;
}

export const GENERATED_HEADER =
  '/** Generated by packages/video.js/scripts/generate-html-entries.ts — do not edit. */\n\n';

/** Subdirectory of `dist/<mode>/` and `src/` that holds the generated mirror of `@videojs/html`. */
export const HTML_DIR = 'html';

const DIST_TARGET = /^\.\/dist\/(\*|dev|default)\//;

/**
 * Moves a `@videojs/html` dist path under the `html/` subtree so hand-written `video.js` modules never collide with
 * generated ones: `./dist/dev/define/video/*.js` → `./dist/dev/html/define/video/*.js`.
 */
export function rewriteHtmlDistPath(path: string): string {
  return path.replace(DIST_TARGET, `./dist/$1/${HTML_DIR}/`);
}

function rewriteTarget(target: ExportTarget): ExportTarget {
  if (isString(target)) return rewriteHtmlDistPath(target);

  return Object.fromEntries(Object.entries(target).map(([condition, path]) => [condition, rewriteHtmlDistPath(path)]));
}

/**
 * Entries owned by `video.js` itself, never mirrored from `@videojs/html`. Listed first so they read as the package's
 * own surface.
 */
const OWN_EXPORTS = {
  './package.json': './package.json',
  // Re-exports `@videojs/html` and adds the coded Video.js 8 stubs (`videojs()`, `registerPlugin`, …).
  '.': {
    types: './dist/dev/index.d.ts',
    development: './dist/dev/index.js',
    default: './dist/default/index.js',
  },
  './errors': {
    types: './dist/dev/errors/index.d.ts',
    development: './dist/dev/errors/index.js',
    default: './dist/default/errors/index.js',
  },
  // The Video.js 8 stylesheet path. Resolving to an empty file keeps a stale import from failing at module resolution,
  // before the `videojs()` stub can explain what changed.
  './dist/video-js.css': './dist/video-js.css',
} satisfies ExportsMap;

export function isOwnExport(key: string): boolean {
  return Object.hasOwn(OWN_EXPORTS, key);
}

/** The manifest fields `video.js` mirrors from `@videojs/html`. */
export function buildPackageFields(html: HtmlPackageJson) {
  const mirrored = Object.entries(html.exports)
    .filter(([key]) => !isOwnExport(key))
    .map(([key, target]) => [key, rewriteTarget(target)] as const);

  return {
    main: 'dist/default/index.js',
    module: 'dist/default/index.js',
    types: 'dist/dev/index.d.ts',
    sideEffects: html.sideEffects.map(rewriteHtmlDistPath),
    exports: { ...OWN_EXPORTS, ...Object.fromEntries(mirrored) },
    peerDependencies: html.peerDependencies ?? {},
    peerDependenciesMeta: html.peerDependenciesMeta ?? {},
  };
}

function isEntrySource(file: string): boolean {
  return (
    file.endsWith('.ts') && !file.endsWith('.d.ts') && !file.endsWith('.test.ts') && !file.includes(`${sep}tests${sep}`)
  );
}

function walk(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) return files;

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);

    if (statSync(full).isDirectory()) {
      walk(full, files);
    } else if (isEntrySource(full)) {
      files.push(full);
    }
  }

  return files;
}

const ANY_EXPORT = /^export\b/m;
const DEFAULT_EXPORT = /export\s+default\b|export\s*\{[^}]*\bdefault\b/;

function inspectExports(file: string): Pick<HtmlModule, 'hasExports' | 'hasDefault'> {
  const source = readFileSync(file, 'utf8');

  return { hasExports: ANY_EXPORT.test(source), hasDefault: DEFAULT_EXPORT.test(source) };
}

/**
 * Inverts `@videojs/html`'s export map against its source tree: every module a public specifier can reach, paired with
 * that specifier. Where several keys reach the same module, the one with the longest literal prefix wins, matching
 * Node's own precedence.
 */
export function resolveHtmlModules(htmlSrcDir: string, exports: ExportsMap): HtmlModule[] {
  const found = new Map<string, HtmlModule & { specificity: number }>();

  const add = (modulePath: string, specifier: string, specificity: number, source: string) => {
    const existing = found.get(modulePath);
    if (existing && existing.specificity >= specificity) return;

    found.set(modulePath, { modulePath, specifier, specificity, ...inspectExports(source) });
  };

  for (const [key, target] of Object.entries(exports)) {
    if (isOwnExport(key)) continue;

    const dist = isString(target) ? target : target.default;
    if (!dist || !dist.endsWith('.js')) continue;

    const pattern = dist.replace(DIST_TARGET, '').replace(/\.js$/, '');
    const specifierBase = `@videojs/html${key.slice(1)}`;

    if (!pattern.includes('*')) {
      const source = join(htmlSrcDir, `${pattern}.ts`);
      if (!isEntrySource(source) || !existsSync(source)) continue;

      add(pattern, specifierBase, Number.POSITIVE_INFINITY, source);
      continue;
    }

    const [prefix = '', suffix = ''] = pattern.split('*');

    for (const source of walk(join(htmlSrcDir, prefix))) {
      const modulePath = relative(htmlSrcDir, source).split(sep).join('/').replace(/\.ts$/, '');
      if (!modulePath.startsWith(prefix) || !modulePath.endsWith(suffix)) continue;

      const star = modulePath.slice(prefix.length, modulePath.length - suffix.length);
      if (!star) continue;

      add(modulePath, specifierBase.replace('*', star), prefix.length, source);
    }
  }

  return [...found.values()]
    .map(({ specificity: _, ...module }) => module)
    .sort((a, b) => a.modulePath.localeCompare(b.modulePath));
}

/** Source of one generated re-export module. */
export function renderHtmlEntry({ specifier, hasExports, hasDefault }: HtmlModule): string {
  if (!hasExports) return `${GENERATED_HEADER}import '${specifier}';\n`;

  const lines = [`export * from '${specifier}';`];

  if (hasDefault) lines.push(`export { default } from '${specifier}';`);

  return `${GENERATED_HEADER}${lines.join('\n')}\n`;
}
