// Generated by @videojs/compiler. Do not edit.

import { isString } from '@videojs/utils/predicate';
import { cn } from '@videojs/utils/style';
import type { ReactNode } from 'react';
import {
  AirPlayEnterIcon,
  AirPlayExitIcon,
  CaptionsOffIcon,
  CaptionsOnIcon,
  CastEnterIcon,
  CastExitIcon,
  ChevronIcon,
  FullscreenEnterIcon,
  FullscreenExitIcon,
  PauseIcon,
  PipEnterIcon,
  PipExitIcon,
  PlayIcon,
  RestartIcon,
  SeekIcon,
  SpinnerIcon,
  VolumeHighIcon,
  VolumeLowIcon,
  VolumeOffIcon,
} from '@/icons';
import { Container } from '@/player/context';
import { AirPlayButton } from '@/ui/airplay-button';
import { BufferingIndicator } from '@/ui/buffering-indicator';
import { CastButton } from '@/ui/cast-button';
import { Controls } from '@/ui/controls';
import { ErrorDialog } from '@/ui/error-dialog';
import { FeatureAvailability } from '@/ui/feature-availability';
import { FullscreenButton } from '@/ui/fullscreen-button';
import { Gesture } from '@/ui/gesture';
import { Hotkey } from '@/ui/hotkey';
import { MuteButton } from '@/ui/mute-button';
import { Overlay } from '@/ui/overlay';
import { PiPButton } from '@/ui/pip-button';
import { PlayButton } from '@/ui/play-button';
import { Popover } from '@/ui/popover';
import { Poster } from '@/ui/poster';
import { SeekButton } from '@/ui/seek-button';
import { SeekIndicator } from '@/ui/seek-indicator';
import { Slider } from '@/ui/slider';
import { StatusAnnouncer } from '@/ui/status-announcer';
import { StatusIndicator } from '@/ui/status-indicator';
import { Time } from '@/ui/time';
import { TimeSlider } from '@/ui/time-slider';
import { Tooltip } from '@/ui/tooltip';
import { VolumeIndicator } from '@/ui/volume-indicator';
import { VolumeSlider } from '@/ui/volume-slider';
import { isRenderProp } from '@/utils/use-render';
import type { BaseVideoSkinProps } from '../../types';

const SEEK_TIME = 10;

const TOP_STATUS_ACTIONS = ['toggleSubtitles', 'toggleFullscreen', 'togglePictureInPicture'] as const;

const CENTER_STATUS_ACTIONS = ['togglePaused'] as const;

export interface DefaultVideoSkinProps extends BaseVideoSkinProps {
  className?: string;
  children?: ReactNode | undefined;
}

function MuteControl() {
  return (
    <MuteButton className="media-button">
      <VolumeOffIcon className="media-volume-off-icon" />
      <VolumeLowIcon className="media-volume-low-icon" />
      <VolumeHighIcon className="media-volume-high-icon" />
    </MuteButton>
  );
}

export function DefaultVideoSkin({ className, children, poster, ...rest }: DefaultVideoSkinProps) {
  return (
    <Container className={cn('media-root', className)} {...rest}>
      {children}

      {poster && (
        <Poster src={isString(poster) ? poster : undefined} render={isRenderProp(poster) ? poster : undefined} />
      )}

      <BufferingIndicator className="media-buffering">
        <SpinnerIcon className="media-icon" />
      </BufferingIndicator>

      <ErrorDialog.Root>
        <ErrorDialog.Popup className="media-error">
          <ErrorDialog.Title className="media-error-title">Something went wrong.</ErrorDialog.Title>
          <ErrorDialog.Description className="media-error-description" />
          <ErrorDialog.Close className="media-error-close media-button">OK</ErrorDialog.Close>
        </ErrorDialog.Popup>
      </ErrorDialog.Root>

      <Controls.Root className="media-controls" data-controls="">
        <Tooltip.Provider>
          <Controls.Group className="media-controls-group-start media-controls-group">
            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <PlayButton className="media-button">
                    <RestartIcon className="media-restart-icon" />
                    <PlayIcon className="media-play-icon" />
                    <PauseIcon className="media-pause-icon" />
                  </PlayButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <SeekButton seconds={-SEEK_TIME} className="media-button">
                    <SeekIcon className="media-seek-backward-icon" />
                    <span className="media-seek-label-backward media-seek-label">{SEEK_TIME}</span>
                  </SeekButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <SeekButton seconds={SEEK_TIME} className="media-button">
                    <SeekIcon className="media-icon" />
                    <span className="media-seek-label-forward media-seek-label">{SEEK_TIME}</span>
                  </SeekButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>
          </Controls.Group>

          <Time.Group className="media-time-group">
            <Time.Value type="current" className="media-time-current" />
            <TimeSlider.Root className="media-slider">
              <TimeSlider.Track className="media-slider-track">
                <TimeSlider.Fill className="media-slider-fill" />
                <TimeSlider.Buffer className="media-slider-buffer" />
              </TimeSlider.Track>
              <TimeSlider.Thumb className="media-slider-thumb" />
              <Slider.Thumbnail.Root className="media-slider-thumbnail">
                <Slider.Thumbnail.Image className="media-slider-thumbnail-image" />
                <TimeSlider.Value type="pointer" className="media-slider-thumbnail-time" />
                <SpinnerIcon className="media-spinner" />
              </Slider.Thumbnail.Root>
              <TimeSlider.Preview className="media-slider-preview">
                <TimeSlider.Value type="pointer" className="media-slider-value" />
              </TimeSlider.Preview>
            </TimeSlider.Root>
            <Time.Value type="duration" className="media-time-duration" />
          </Time.Group>

          <Controls.Group className="media-controls-group-end media-controls-group">
            <FeatureAvailability is="volume" when="unsupported">
              <MuteControl />
            </FeatureAvailability>
            <FeatureAvailability is="volume" except="unsupported">
              <Popover.Root openOnHover delay={200} closeDelay={100} side="top">
                <Popover.Trigger render={<MuteControl />} />
                <Popover.Popup className="media-volume-popover media-popover">
                  <VolumeSlider.Root orientation="vertical" thumbAlignment="edge" className="media-slider">
                    <VolumeSlider.Track className="media-slider-track">
                      <VolumeSlider.Fill className="media-slider-fill" />
                    </VolumeSlider.Track>
                    <VolumeSlider.Thumb className="media-slider-thumb-persistent media-slider-thumb" />
                  </VolumeSlider.Root>
                </Popover.Popup>
              </Popover.Root>
            </FeatureAvailability>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <CastButton className="media-button">
                    <CastEnterIcon className="media-cast-enter-icon" />
                    <CastExitIcon className="media-cast-exit-icon" />
                  </CastButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <AirPlayButton className="media-button">
                    <AirPlayEnterIcon className="media-airplay-enter-icon" />
                    <AirPlayExitIcon className="media-airplay-exit-icon" />
                  </AirPlayButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <PiPButton className="media-button">
                    <PipEnterIcon className="media-pip-enter-icon" />
                    <PipExitIcon className="media-pip-exit-icon" />
                  </PiPButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>

            <Tooltip.Root side="top">
              <Tooltip.Trigger
                render={
                  <FullscreenButton className="media-button">
                    <FullscreenEnterIcon className="media-fullscreen-enter-icon" />
                    <FullscreenExitIcon className="media-fullscreen-exit-icon" />
                  </FullscreenButton>
                }
              />
              <Tooltip.Popup className="media-tooltip">
                <Tooltip.Label />
                <Tooltip.Shortcut className="media-tooltip-shortcut" />
              </Tooltip.Popup>
            </Tooltip.Root>
          </Controls.Group>
        </Tooltip.Provider>
      </Controls.Root>

      <Overlay className="media-overlay" />

      <Hotkey keys="Space" action="togglePaused" />
      <Hotkey keys="k" action="togglePaused" />
      <Hotkey keys="m" action="toggleMuted" />
      <Hotkey keys="f" action="toggleFullscreen" />
      <Hotkey keys="c" action="toggleSubtitles" />
      <Hotkey keys="i" action="togglePictureInPicture" />
      <Hotkey keys="ArrowRight" action="seekStep" value={SEEK_TIME / 2} />
      <Hotkey keys="ArrowLeft" action="seekStep" value={-(SEEK_TIME / 2)} />
      <Hotkey keys="l" action="seekStep" value={SEEK_TIME} />
      <Hotkey keys="j" action="seekStep" value={-SEEK_TIME} />
      <Hotkey keys="ArrowUp" action="volumeStep" value={0.05} />
      <Hotkey keys="ArrowDown" action="volumeStep" value={-0.05} />
      <Hotkey keys="0-9" action="seekToPercent" />
      <Hotkey keys="Home" action="seekToPercent" value={0} />
      <Hotkey keys="End" action="seekToPercent" value={100} />
      <Hotkey keys=">" action="speedUp" />
      <Hotkey keys="<" action="speedDown" />

      <Gesture type="tap" action="togglePaused" pointer="mouse" region="center" />
      <Gesture type="tap" action="toggleControls" pointer="touch" />
      <Gesture type="doubletap" action="seekStep" value={-SEEK_TIME} region="left" />
      <Gesture type="doubletap" action="toggleFullscreen" region="center" />
      <Gesture type="doubletap" action="seekStep" value={SEEK_TIME} region="right" />

      <StatusAnnouncer />

      <VolumeIndicator.Root className="media-volume-indicator">
        <VolumeIndicator.Fill className="media-indicator-content">
          <VolumeHighIcon className="media-volume-indicator-high-icon" />
          <VolumeLowIcon className="media-volume-indicator-low-icon" />
          <VolumeOffIcon className="media-volume-indicator-off-icon" />
          <VolumeIndicator.Value className="media-indicator-value" />
        </VolumeIndicator.Fill>
      </VolumeIndicator.Root>

      <StatusIndicator.Root actions={TOP_STATUS_ACTIONS} className="media-status-indicator-top media-status-indicator">
        <CaptionsOnIcon className="media-status-indicator-captions-on-icon" />
        <CaptionsOffIcon className="media-status-indicator-captions-off-icon" />
        <FullscreenEnterIcon className="media-status-indicator-fullscreen-enter-icon" />
        <FullscreenExitIcon className="media-status-indicator-fullscreen-exit-icon" />
        <PipEnterIcon className="media-status-indicator-pip-enter-icon" />
        <PipExitIcon className="media-status-indicator-pip-exit-icon" />
        <StatusIndicator.Value className="media-indicator-value" />
      </StatusIndicator.Root>

      <SeekIndicator.Root className="media-seek-indicator">
        <ChevronIcon className="media-seek-indicator-icon" />
        <SeekIndicator.Value className="media-seek-indicator-value" />
      </SeekIndicator.Root>

      <StatusIndicator.Root
        actions={CENTER_STATUS_ACTIONS}
        className="media-status-indicator-center media-status-indicator"
      >
        <PlayIcon className="media-status-indicator-play-icon" />
        <PauseIcon className="media-status-indicator-pause-icon" />
      </StatusIndicator.Root>
    </Container>
  );
}
