import type { Sidebar } from '@/types/docs';

/**
 * Top-level sections render as tabs at the top of the docs sidebar ("Guide", "Components"). Everything below a tab
 * renders flat: second-level sections are headings, third-level sections are sub-headings. There is nothing to expand
 * or collapse.
 */
export const sidebar: Sidebar = [
  {
    sidebarLabel: 'Guide',
    llmsDescription: 'Installation, migration, concepts, playback guides, customization, and tooling for Video.js.',
    contents: [
      {
        sidebarLabel: 'Getting Started',
        llmsDescription: 'Install Video.js and understand its main pieces.',
        contents: [
          { slug: 'guides/installation' },
          { slug: 'guides/installation-vue', sidebarLabel: 'Install with Vue', frameworks: ['html'], hidden: true },
          {
            slug: 'guides/installation-svelte',
            sidebarLabel: 'Install with Svelte',
            frameworks: ['html'],
            hidden: true,
          },
          { slug: 'concepts/overview' },
          { slug: 'concepts/why-videojs' },
          { slug: 'concepts/v10-roadmap', sidebarLabel: 'Roadmap' },
        ],
      },
      {
        sidebarLabel: 'Tooling',
        llmsDescription:
          'Guidance for AI tools, browser support, TypeScript, bundlers, the CDN, self-hosting, and contributing.',
        contents: [
          { slug: 'guides/build-with-ai' },
          { slug: 'concepts/browser-support' },
          { slug: 'concepts/typescript' },
          { slug: 'concepts/bundlers' },
          { slug: 'concepts/cdn', frameworks: ['html'] },
          { slug: 'guides/self-host-the-player', sidebarLabel: 'Self-hosting', frameworks: ['html'] },
          { href: 'https://github.com/videojs/v10/blob/main/CONTRIBUTING.md', sidebarLabel: 'Contribute to Video.js' },
        ],
      },
      {
        sidebarLabel: 'Migrate',
        llmsDescription:
          'Guides for moving an existing player integration to Video.js v10, one per player you might be coming from.',
        contents: [
          { slug: 'guides/migrate-from-video-js-8', sidebarLabel: 'From Video.js 8' },
          { slug: 'guides/migrate-from-mux-player', sidebarLabel: 'From Mux Player' },
          { slug: 'guides/migrate-from-plyr', sidebarLabel: 'From Plyr' },
          { slug: 'guides/migrate-from-media-chrome', sidebarLabel: 'From Media Chrome' },
        ],
      },
      {
        sidebarLabel: 'Concepts',
        llmsDescription:
          'Understanding-oriented pages that explain how and why things work. Read these to build a mental model of the library.',
        contents: [
          { slug: 'concepts/features' },
          { slug: 'concepts/skins' },
          { slug: 'concepts/presets' },
          { slug: 'concepts/ui-components' },
          { slug: 'concepts/accessibility' },
          { slug: 'concepts/media-sources' },
          { slug: 'concepts/mux-data' },
          { slug: 'concepts/security' },
          { slug: 'concepts/custom-element-lifecycle', frameworks: ['html'] },
        ],
      },
      {
        sidebarLabel: 'Playback',
        llmsDescription:
          'Guides for one player capability each: the recommended setup, how it works, browser constraints, variations, and troubleshooting.',
        contents: [
          { slug: 'guides/autoplay', sidebarLabel: 'Autoplay' },
          { slug: 'guides/show-and-hide-controls', sidebarLabel: 'Controls' },
          { slug: 'guides/add-a-poster-and-loading-placeholder', sidebarLabel: 'Poster and placeholder' },
          { slug: 'guides/show-captions-and-subtitles', sidebarLabel: 'Captions and subtitles' },
          { slug: 'guides/add-keyboard-shortcuts-and-gestures', sidebarLabel: 'Keyboard shortcuts and gestures' },
          { slug: 'guides/play-live-streams', sidebarLabel: 'Live streams' },
          { slug: 'guides/add-quality-selector', sidebarLabel: 'Quality selector' },
          { slug: 'guides/go-fullscreen-and-lock-orientation', sidebarLabel: 'Fullscreen and orientation' },
          { slug: 'guides/use-picture-in-picture', sidebarLabel: 'Picture-in-picture' },
          { slug: 'guides/show-timeline-thumbnail-previews', sidebarLabel: 'Thumbnail previews' },
          { slug: 'guides/cast-to-airplay-and-chromecast', sidebarLabel: 'AirPlay and Chromecast' },
          { slug: 'guides/handle-playback-errors', sidebarLabel: 'Playback errors' },
          { slug: 'guides/remember-user-preferences', sidebarLabel: 'User preferences' },
          { slug: 'guides/add-a-background-video', sidebarLabel: 'Background video' },
          { slug: 'guides/internationalize-the-player', sidebarLabel: 'Internationalization' },
        ],
      },
      {
        sidebarLabel: 'Customize',
        llmsDescription: 'Guides for changing what the player looks like and building your own controls.',
        contents: [
          { slug: 'guides/customize-skins', sidebarLabel: 'Customize skins' },
          { slug: 'guides/build-your-own-component', sidebarLabel: 'Build a component' },
        ],
      },
      {
        sidebarLabel: 'Frameworks',
        frameworks: ['html'],
        llmsDescription: 'Guides for using the HTML version of Video.js with Vue, Nuxt, Svelte, or SvelteKit.',
        contents: [
          { slug: 'guides/use-videojs-with-vue', sidebarLabel: 'Vue and Nuxt' },
          { slug: 'guides/use-videojs-with-svelte', sidebarLabel: 'Svelte and SvelteKit' },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'Components',
    llmsDescription:
      'API reference for skins, media components, extensions, interface components, player features, and utilities.',
    contents: [
      {
        sidebarLabel: 'Skins',
        llmsDescription: 'API reference for the packaged skins each preset ships.',
        contents: [
          { slug: 'components/video-skin' },
          { slug: 'components/video-minimal-skin' },
          { slug: 'components/audio-skin' },
          { slug: 'components/audio-minimal-skin' },
          { slug: 'components/live-video-skin' },
          { slug: 'components/live-video-minimal-skin' },
          { slug: 'components/live-audio-skin' },
          { slug: 'components/live-audio-minimal-skin' },
          { slug: 'components/background-video-skin' },
        ],
      },
      {
        sidebarLabel: 'Media',
        llmsDescription: 'API reference for media components that handle streaming protocols and playback.',
        contents: [
          { slug: 'components/audio' },
          { slug: 'components/background-video' },
          { slug: 'components/cloudflare-video' },
          { slug: 'components/dash-video' },
          { slug: 'components/hls-audio' },
          { slug: 'components/hls-background-video' },
          { slug: 'components/hls-video' },
          { slug: 'components/hlsjs-video' },
          { slug: 'components/mux-audio' },
          { slug: 'components/mux-background-video' },
          { slug: 'components/mux-video' },
          { slug: 'components/native-hls-video' },
          { slug: 'components/shaka-video' },
          { slug: 'components/spotify-audio' },
          { slug: 'components/tiktok-video' },
          { slug: 'components/twitch-video' },
          { slug: 'components/video' },
          { slug: 'components/vimeo-video' },
          { slug: 'components/wistia-video' },
          { slug: 'components/youtube-video' },
        ],
      },
      {
        sidebarLabel: 'Extensions',
        llmsDescription: 'API reference for extensions that connect external services to the player.',
        contents: [{ slug: 'components/google-cast' }, { slug: 'components/mux-data' }],
      },
      {
        sidebarLabel: 'Layout',
        llmsDescription: 'API reference for the components that establish a player and lay out its interface.',
        contents: [
          { slug: 'components/player' },
          { slug: 'components/player-container' },
          { slug: 'components/controls' },
        ],
      },
      {
        sidebarLabel: 'Buttons',
        llmsDescription: 'API reference for the button components that trigger playback actions.',
        contents: [
          { slug: 'components/play-button' },
          { slug: 'components/mute-button' },
          { slug: 'components/seek-button' },
          { slug: 'components/fullscreen-button' },
          { slug: 'components/pip-button' },
          { slug: 'components/captions-button' },
          { slug: 'components/playback-rate-button' },
          { slug: 'components/live-button' },
          { slug: 'components/airplay-button' },
          { slug: 'components/cast-button' },
        ],
      },
      {
        sidebarLabel: 'Sliders',
        llmsDescription: 'API reference for the slider components that scrub time and adjust volume.',
        contents: [
          { slug: 'components/slider' },
          { slug: 'components/time-slider' },
          { slug: 'components/volume-slider' },
        ],
      },
      {
        sidebarLabel: 'Menus',
        llmsDescription:
          'API reference for menus, popovers, and the radio groups that pick tracks, quality, and speed.',
        contents: [
          { slug: 'components/menu' },
          { slug: 'components/popover' },
          { slug: 'components/volume-popover' },
          { slug: 'components/audio-track-radio-group' },
          { slug: 'components/captions-radio-group' },
          { slug: 'components/playback-rate-radio-group' },
          { slug: 'components/quality-radio-group' },
        ],
      },
      {
        sidebarLabel: 'Display',
        llmsDescription: 'API reference for components that display player state, media metadata, and previews.',
        contents: [
          { slug: 'components/time' },
          { slug: 'components/title' },
          { slug: 'components/poster' },
          { slug: 'components/thumbnail' },
          { slug: 'components/tooltip' },
          { slug: 'components/buffering-indicator' },
          { slug: 'components/seek-indicator' },
          { slug: 'components/status-indicator' },
          { slug: 'components/volume-indicator' },
        ],
      },
      {
        sidebarLabel: 'Dialogs',
        llmsDescription: 'API reference for modal dialogs, alerts, and playback error surfaces.',
        contents: [
          { slug: 'components/dialog' },
          { slug: 'components/alert-dialog' },
          { slug: 'components/error-dialog' },
        ],
      },
      {
        sidebarLabel: 'Behavior',
        llmsDescription: 'API reference for the non-visual components that add gestures, hotkeys, and announcements.',
        contents: [
          { slug: 'components/gesture' },
          { slug: 'components/hotkey' },
          { slug: 'components/status-announcer' },
        ],
      },
      {
        sidebarLabel: 'Player Features',
        llmsDescription:
          'API reference for the feature modules passed to createPlayer, which provide player capabilities and state.',
        contents: [
          { slug: 'components/create-selector' },
          { slug: 'components/feature-buffer' },
          { slug: 'components/feature-controls' },
          { slug: 'components/feature-error' },
          { slug: 'components/feature-fullscreen' },
          { slug: 'components/feature-live' },
          { slug: 'components/feature-metadata' },
          { slug: 'components/feature-orientation-lock' },
          { slug: 'components/feature-pip', sidebarLabel: 'Picture-in-picture' },
          { slug: 'components/feature-playback' },
          { slug: 'components/feature-playback-rate' },
          { slug: 'components/feature-quality' },
          { slug: 'components/feature-audio-track' },
          { slug: 'components/feature-remote-playback' },
          { slug: 'components/feature-source' },
          { slug: 'components/feature-stream-type' },
          { slug: 'components/feature-text-tracks' },
          { slug: 'components/feature-time' },
          { slug: 'components/feature-volume' },
        ],
      },
      {
        sidebarLabel: 'Utilities',
        llmsDescription:
          'API reference for the hooks, utilities, controllers, and mixins used to integrate a player into an application.',
        contents: [
          { slug: 'components/create-player', frameworks: ['react'] },
          { slug: 'components/html-create-player', sidebarLabel: 'createPlayer', frameworks: ['html'] },
          { slug: 'components/player-controller', frameworks: ['html'] },
          { slug: 'components/use-player', frameworks: ['react'] },
          { slug: 'components/use-media', frameworks: ['react'] },
          { slug: 'components/use-container', frameworks: ['react'] },
          { slug: 'components/use-store', frameworks: ['react'] },
        ],
      },
      {
        sidebarLabel: 'Hooks',
        frameworks: ['react'],
        llmsDescription: 'API reference for the lower-level React hooks behind the components and player integration.',
        contents: [
          { slug: 'components/use-attach-media' },
          { slug: 'components/use-audio-track-options' },
          { slug: 'components/use-button' },
          { slug: 'components/use-captions-options' },
          { slug: 'components/use-composed-refs' },
          { slug: 'components/use-container-attach' },
          { slug: 'components/use-destroy' },
          { slug: 'components/use-dialog-context' },
          { slug: 'components/use-double-tap-gesture' },
          { slug: 'components/use-error-dialog-context' },
          { slug: 'components/use-hotkey' },
          { slug: 'components/use-hotkey-shortcut' },
          { slug: 'components/use-latest-ref' },
          { slug: 'components/use-media-attach' },
          { slug: 'components/use-media-extension' },
          { slug: 'components/use-media-instance' },
          { slug: 'components/use-menu-context' },
          { slug: 'components/use-optional-container' },
          { slug: 'components/use-optional-menu-context' },
          { slug: 'components/use-optional-player' },
          { slug: 'components/use-playback-rate-options' },
          { slug: 'components/use-player-context' },
          { slug: 'components/use-popover-context' },
          { slug: 'components/use-quality-options' },
          { slug: 'components/use-selector' },
          { slug: 'components/use-slider' },
          { slug: 'components/use-snapshot' },
          { slug: 'components/use-tap-gesture' },
          { slug: 'components/use-tooltip-context' },
        ],
      },
      {
        sidebarLabel: 'Controllers',
        frameworks: ['html'],
        llmsDescription: 'API reference for the reactive controllers that connect custom elements to player state.',
        contents: [
          { slug: 'components/aria-key-shortcuts-controller' },
          { slug: 'components/snapshot-controller' },
          { slug: 'components/store-controller' },
          { slug: 'components/subscription-controller' },
        ],
      },
      {
        sidebarLabel: 'i18n',
        llmsDescription:
          'API reference for translating the player: providers, hooks, elements, the phrase registry, and contexts.',
        contents: [
          { slug: 'components/i18n-provider', frameworks: ['react'] },
          { slug: 'components/create-i18n' },
          { slug: 'components/use-translator', frameworks: ['react'] },
          { slug: 'components/use-locale', frameworks: ['react'] },
          { slug: 'components/media-i18n', sidebarLabel: 'media-i18n', frameworks: ['html'] },
          { slug: 'components/media-text', sidebarLabel: 'media-text', frameworks: ['html'] },
          { slug: 'components/translation-phrases', sidebarLabel: 'Translation keys' },
          { slug: 'components/register-i18n', sidebarLabel: 'registerI18n' },
          { slug: 'components/get-i18n-translations', sidebarLabel: 'getI18nTranslations' },
          { slug: 'components/has-registered-locale', sidebarLabel: 'hasRegisteredLocale' },
          { slug: 'components/on-i18n-registry-change', sidebarLabel: 'onI18nRegistryChange' },
          { slug: 'components/create-translator', sidebarLabel: 'createTranslator' },
          { slug: 'components/i-18-n-context', sidebarLabel: 'I18nContext', frameworks: ['react'] },
          { slug: 'components/html-i-18-n-context', sidebarLabel: 'i18nContext', frameworks: ['html'] },
          { slug: 'components/i-18-n-controller', sidebarLabel: 'I18nController' },
        ],
      },
      {
        sidebarLabel: 'Advanced',
        llmsDescription: 'Lower-level translation, player context, lifecycle, attachment, and state tools.',
        contents: [
          { slug: 'components/merge-props', frameworks: ['react'] },
          { slug: 'components/render-element', frameworks: ['react'] },
          { slug: 'components/media-attach-mixin', frameworks: ['html'] },
          { slug: 'components/player-context', frameworks: ['html'] },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'Writing Style',
    devOnly: true,
    llmsDescription: 'Guides for people writing this documentation site.',
    contents: [
      {
        sidebarLabel: 'Authoring',
        contents: [
          { slug: 'writing-style/write-guides', sidebarLabel: 'Writing guides' },
          { slug: 'writing-style/write-references', sidebarLabel: 'Writing references' },
        ],
      },
    ],
  },
];
