import type { Sidebar } from '@/types/docs';

export const sidebar: Sidebar = [
  {
    sidebarLabel: 'Site development',
    devOnly: true,
    contents: [
      {
        slug: 'how-to/write-guides',
        sidebarLabel: 'Writing guides',
        devOnly: true,
      },
      {
        slug: 'reference/write-references',
        sidebarLabel: 'Writing references',
        devOnly: true,
      },
    ],
  },
  {
    sidebarLabel: 'Getting started',
    // May change when we revisit this section's boundary with Concepts (#1105)
    llmsDescription: 'Installation, project setup, and introductory guides.',
    contents: [
      { slug: 'how-to/installation' },
      { slug: 'concepts/why-videojs' },
      { slug: 'concepts/overview' },
      { slug: 'how-to/build-with-ai' },
      { slug: 'concepts/v10-roadmap', sidebarLabel: 'Roadmap' },
      { href: '/changelog', sidebarLabel: 'Changelog' },
      { slug: 'concepts/browser-support' },
    ],
  },
  {
    sidebarLabel: 'How to',
    llmsDescription:
      "Task-oriented guides that each fully answer one goal in the reader's words. Guides assume you are building your own player UI with the Video.js UI library. Each guide states the recommended implementation, availability and constraints, variations, and troubleshooting.",
    contents: [
      { slug: 'how-to/load-different-file-formats' },
      { slug: 'how-to/autoplay' },
      { slug: 'how-to/play-live-streams' },
      { slug: 'how-to/go-fullscreen-and-lock-orientation' },
      { slug: 'how-to/use-picture-in-picture' },
      { slug: 'how-to/cast-to-airplay-and-chromecast' },
      { slug: 'how-to/show-captions-and-subtitles' },
      { slug: 'how-to/show-timeline-thumbnail-previews' },
      { slug: 'how-to/provide-alternative-audio-tracks' },
      { slug: 'how-to/add-quality-selector' },
      { slug: 'how-to/show-poster-before-playback' },
      { slug: 'how-to/show-and-hide-controls' },
      { slug: 'how-to/add-keyboard-shortcuts-and-gestures' },
      { slug: 'how-to/internationalize-the-player' },
      { slug: 'how-to/remember-user-preferences' },
      { slug: 'how-to/handle-playback-errors' },
      { slug: 'how-to/customize-skins' },
      { slug: 'how-to/build-your-own-component' },
      { slug: 'how-to/self-host-the-player', frameworks: ['html'] },
      {
        sidebarLabel: 'Internationalization',
        defaultOpen: false,
        contents: [
          { slug: 'reference/translation-phrases', sidebarLabel: 'Translation keys' },
          { slug: 'how-to/i18n-register-locale', sidebarLabel: 'Register a locale' },
          { slug: 'how-to/i18n-override-translations', sidebarLabel: 'Override translations' },
          { slug: 'how-to/i18n-switch-locale', sidebarLabel: 'Switch locale' },
          { slug: 'how-to/i18n-ssr', sidebarLabel: 'SSR with locale' },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'Concepts',
    llmsDescription:
      'Understanding-oriented pages that explain how and why things work. Read these to build a mental model of the library.',
    contents: [
      { slug: 'concepts/features' },
      { slug: 'concepts/skins' },
      { slug: 'concepts/presets' },
      { slug: 'concepts/ui-components' },
      { slug: 'concepts/accessibility' },
      { slug: 'concepts/media-sources' },
      { slug: 'concepts/cast', sidebarLabel: 'Google Cast' },
      { slug: 'concepts/mux-data' },
      { slug: 'concepts/security' },
      { slug: 'concepts/i18n', sidebarLabel: 'Internationalization' },
    ],
  },
  {
    sidebarLabel: 'Components',
    llmsDescription: 'API Reference for UI components for building media player interfaces.',
    contents: [
      { slug: 'reference/player-provider' },
      { slug: 'reference/player-container' },
      { slug: 'reference/i18n-provider', frameworks: ['react'] },
      // sorted alphabetically
      { slug: 'reference/airplay-button' },
      { slug: 'reference/audio-track-radio-group' },
      { slug: 'reference/buffering-indicator' },
      { slug: 'reference/captions-button' },
      { slug: 'reference/captions-radio-group' },
      { slug: 'reference/cast-button' },
      { slug: 'reference/controls' },
      { slug: 'reference/fullscreen-button' },
      { slug: 'reference/google-cast' },
      { slug: 'reference/menu' },
      { slug: 'reference/mute-button' },
      { slug: 'reference/mux-data' },
      { slug: 'reference/pip-button' },
      { slug: 'reference/play-button' },
      { slug: 'reference/playback-rate-button' },
      { slug: 'reference/playback-rate-radio-group' },
      { slug: 'reference/popover' },
      { slug: 'reference/poster' },
      { slug: 'reference/quality-radio-group' },
      { slug: 'reference/seek-button' },
      { slug: 'reference/slider' },
      { slug: 'reference/thumbnail' },
      { slug: 'reference/time' },
      { slug: 'reference/time-slider' },
      { slug: 'reference/tooltip' },
      { slug: 'reference/volume-slider' },
    ],
  },
  {
    sidebarLabel: 'Media Elements',
    llmsDescription: 'API Reference for media elements that handle streaming protocols and media playback.',
    contents: [
      { slug: 'reference/background-video' },
      { slug: 'reference/dash-video' },
      { slug: 'reference/hlsjs-video' },
      { slug: 'reference/mux-audio' },
      { slug: 'reference/mux-video' },
      { slug: 'reference/native-hls-video' },
      { slug: 'reference/simple-hls-audio-only' },
      { slug: 'reference/simple-hls-video' },
    ],
  },
  {
    sidebarLabel: 'Hooks & Utilities',
    llmsDescription: 'API reference for hooks and utilities for player integration.',
    contents: [
      { slug: 'reference/create-player', frameworks: ['react'] },
      { slug: 'reference/create-i18n' },
      { slug: 'reference/use-translator', frameworks: ['react'] },
      { slug: 'reference/use-locale', frameworks: ['react'] },
      { slug: 'reference/use-player', frameworks: ['react'] },
      { slug: 'reference/use-media', frameworks: ['react'] },
      { slug: 'reference/use-store', frameworks: ['react'] },
      {
        sidebarLabel: 'Advanced',
        defaultOpen: false,
        contents: [
          { slug: 'reference/register-i18n', sidebarLabel: 'registerI18n' },
          { slug: 'reference/get-i18n-translations', sidebarLabel: 'getI18nTranslations' },
          { slug: 'reference/has-registered-locale', sidebarLabel: 'hasRegisteredLocale' },
          { slug: 'reference/on-i18n-registry-change', sidebarLabel: 'onI18nRegistryChange' },
          { slug: 'reference/create-translator', sidebarLabel: 'createTranslator' },
          { slug: 'reference/render-element', frameworks: ['react'] },
          { slug: 'reference/use-audio-track-options', frameworks: ['react'] },
          { slug: 'reference/use-button', frameworks: ['react'] },
          { slug: 'reference/use-captions-options', frameworks: ['react'] },
          { slug: 'reference/use-container-attach', frameworks: ['react'] },
          { slug: 'reference/use-media-attach', frameworks: ['react'] },
          { slug: 'reference/use-playback-rate-options', frameworks: ['react'] },
          { slug: 'reference/use-player-context', frameworks: ['react'] },
          { slug: 'reference/use-quality-options', frameworks: ['react'] },
          { slug: 'reference/use-selector', frameworks: ['react'] },
          { slug: 'reference/use-snapshot', frameworks: ['react'] },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'Controllers & Mixins',
    llmsDescription: 'API Reference for controllers and mixins for HTML custom element integration.',
    frameworks: ['html'],
    contents: [
      { slug: 'reference/html-create-player', sidebarLabel: 'createPlayer' },
      { slug: 'reference/media-i18n', sidebarLabel: 'media-i18n' },
      { slug: 'reference/media-text', sidebarLabel: 'media-text' },
      { slug: 'reference/player-controller' },
      {
        sidebarLabel: 'Advanced',
        defaultOpen: false,
        contents: [
          { slug: 'reference/container-mixin' },
          { slug: 'reference/media-attach-mixin' },
          { slug: 'reference/player-context' },
          { slug: 'reference/provider-mixin' },
          { slug: 'reference/snapshot-controller' },
          { slug: 'reference/store-controller' },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'Features',
    llmsDescription: 'API reference for feature modules that provide player capabilities and state.',
    contents: [
      { slug: 'reference/create-selector' },
      { slug: 'reference/feature-buffer' },
      { slug: 'reference/feature-controls' },
      { slug: 'reference/feature-error' },
      { slug: 'reference/feature-fullscreen' },
      { slug: 'reference/feature-live' },
      { slug: 'reference/feature-orientation-lock' },
      { slug: 'reference/feature-pip', sidebarLabel: 'Picture-in-picture' },
      { slug: 'reference/feature-playback' },
      { slug: 'reference/feature-playback-rate' },
      { slug: 'reference/feature-quality' },
      { slug: 'reference/feature-audio-track' },
      { slug: 'reference/feature-remote-playback' },
      { slug: 'reference/feature-source' },
      { slug: 'reference/feature-stream-type' },
      { slug: 'reference/feature-text-tracks' },
      { slug: 'reference/feature-time' },
      { slug: 'reference/feature-volume' },
    ],
  },
];
