import { RuleTester } from "oxlint/plugins-dev";
import { describe, it } from "vite-plus/test";

import { paddingLineBetweenStatementsRule } from "../padding-line-between-statements.ts";

RuleTester.describe = describe;
RuleTester.it = it;

const ruleTester = new RuleTester({
	languageOptions: { parserOptions: { lang: "ts" } },
});

ruleTester.run("padding-line-between-statements", paddingLineBetweenStatementsRule, {
	valid: [
		{
			name: "logical declaration groups",
			code: `function run() {
  const first = createFirst();
  const second = createSecond();

  const unrelated = createUnrelated();

  if (unrelated) {
    use(first, second);
  }

  return unrelated;
}`,
		},
		{
			name: "a later declaration may begin after an expression",
			code: `function run() {
  prepare();
  const result = finish();

  return result;
}`,
		},
		{
			name: "generated source",
			code: `/** Generated by example. */
function run() {
  const result = prepare();
  if (result) return result;
  return null;
}`,
		},
	],
	invalid: [
		{
			name: "declaration group before a return",
			code: `function run() {
  const result = prepare();
  return result;
}`,
			output: `function run() {
  const result = prepare();

  return result;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "control flow between adjacent statements",
			code: `function run() {
  prepare();
  if (ready) {
    use();
  }
  finish();
}`,
			output: `function run() {
  prepare();

  if (ready) {
    use();
  }

  finish();
}`,
			errors: [
				{ messageId: "expectedBlankLine", line: 3 },
				{ messageId: "expectedBlankLine", line: 6 },
			],
		},
		{
			name: "leading comment stays with control flow",
			code: `function run() {
  const result = prepare();
  // Stop when preparation fails.
  if (!result) return;
}`,
			output: `function run() {
  const result = prepare();

  // Stop when preparation fails.
  if (!result) return;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 4 }],
		},
		{
			name: "blank lines inside block comments do not count",
			code: `function run() {
  const result = prepare();
  /* Preparation and validation are separate phases.

     Validation starts here. */
  if (result) use(result);
}`,
			output: `function run() {
  const result = prepare();

  /* Preparation and validation are separate phases.

     Validation starts here. */
  if (result) use(result);
}`,
			errors: [{ messageId: "expectedBlankLine", line: 6 }],
		},
		{
			name: "labeled control flow",
			code: `function run(items: string[]) {
  prepare();
  outer: for (const item of items) {
    if (item) break outer;
  }
  finish();
}`,
			output: `function run(items: string[]) {
  prepare();

  outer: for (const item of items) {
    if (item) break outer;
  }

  finish();
}`,
			errors: [
				{ messageId: "expectedBlankLine", line: 3 },
				{ messageId: "expectedBlankLine", line: 6 },
			],
		},
		{
			name: "statements on the same line",
			code: "function run() { const result = prepare(); if (result) return result; return null; }",
			output:
				"function run() { const result = prepare();\n\n if (result) return result;\n\n return null; }",
			errors: [
				{ messageId: "expectedBlankLine", line: 1 },
				{ messageId: "expectedBlankLine", line: 1 },
			],
		},
	],
});
