import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import en from '../src/core/i18n/locales/en.ts';
import { flattenEntries } from './i18n-utils.ts';

const GENERATED_HEADER = '/** Generated by packages/core/scripts/generate-i18n-types.ts — do not edit. */\n';
const output = resolve(dirname(fileURLToPath(import.meta.url)), '../src/core/i18n/params.generated.ts');

function parameterNames(text: string): string[] {
  return [...text.matchAll(/\{([^{}]+)\}/g)]
    .map(([, name]) => name)
    .filter((name, index, names) => names.indexOf(name) === index);
}

function generate(): string {
  const entries = flattenEntries(en);
  const params = entries
    .map(([key, text]) => {
      const names = parameterNames(text);
      const value = names.length ? `{ ${names.map((name) => `${name}: string | number`).join('; ')} }` : 'never';
      return `  '${key}': ${value};`;
    })
    .join('\n');
  return `${GENERATED_HEADER}
/** Generated translation parameter contract from the English catalogue. */
export interface TranslationParams {
${params}
}
`;
}

writeFileSync(output, generate());
console.log('[generate-i18n-types] Updated generated translation types');
