import { existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import ts from 'typescript';

export interface BulkComponentEntry {
  files: string;
  name: (filename: string) => string;
}

export type ComponentEntry = string | BulkComponentEntry;

export interface ComponentsConfig {
  components: readonly ComponentEntry[];
  output: string;
  runtimeImport?: string | undefined;
}

export interface GenerateComponentsOptions {
  cwd?: string | undefined;
  check?: boolean | undefined;
}

export interface GenerateComponentsResult {
  outputPath: string;
  source: string;
  changed: boolean;
}

interface ManifestComponent {
  kind: 'manifest';
  name: string;
  manifestFrom: string;
}

interface InlineComponent {
  kind: 'inline';
  name: string;
}

type ResolvedComponent = ManifestComponent | InlineComponent;

export function defineComponentsConfig<const Config extends ComponentsConfig | readonly ComponentsConfig[]>(
  config: Config
): Config {
  return config;
}

function isDefineComponentCall(node: ts.Node): node is ts.CallExpression {
  return ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === 'defineComponent';
}

function findDefaultExportCall(sourceFile: ts.SourceFile): ts.CallExpression | null {
  for (const statement of sourceFile.statements) {
    if (!ts.isExportAssignment(statement) || statement.isExportEquals) continue;
    if (isDefineComponentCall(statement.expression)) return statement.expression;
  }
  return null;
}

function parseComponentName(manifestPath: string): string {
  const sourceText = readFileSync(manifestPath, 'utf8');
  const sourceFile = ts.createSourceFile(manifestPath, sourceText, ts.ScriptTarget.Latest, true);
  const call = findDefaultExportCall(sourceFile);

  if (!call) {
    throw new Error(`No \`export default defineComponent(...)\` found in ${manifestPath}`);
  }

  const argument = call.arguments[0];
  if (!argument || !ts.isObjectLiteralExpression(argument)) {
    throw new Error(`defineComponent() in ${manifestPath} must take an object literal`);
  }

  for (const property of argument.properties) {
    if (
      ts.isPropertyAssignment(property) &&
      ts.isIdentifier(property.name) &&
      property.name.text === 'name' &&
      ts.isStringLiteral(property.initializer)
    ) {
      return property.initializer.text;
    }
  }

  throw new Error(`defineComponent() in ${manifestPath} is missing a literal \`name:\` field`);
}

function manifestPathToImport(manifestPath: string, outputFile: string): string {
  return normalizeImportPath(relative(dirname(outputFile), manifestPath));
}

export function normalizeImportPath(path: string): string {
  let normalized = path.replaceAll('\\', '/');
  if (!normalized.startsWith('.')) normalized = `./${normalized}`;
  return normalized.replace(/\.[cm]?tsx?$/, '');
}

function fileStem(filePath: string): string {
  const filename = basename(filePath);
  const extension = extname(filename);
  return extension ? filename.slice(0, -extension.length) : filename;
}

function resolveManifestEntry(pattern: string, cwd: string, outputAbsolute: string): ManifestComponent[] {
  const matches = globSync(pattern, { cwd }).map((path) => (isAbsolute(path) ? path : resolve(cwd, path)));
  return matches.map((manifestPath) => ({
    kind: 'manifest',
    name: parseComponentName(manifestPath),
    manifestFrom: manifestPathToImport(manifestPath, outputAbsolute),
  }));
}

function resolveBulkEntry(entry: BulkComponentEntry, cwd: string): InlineComponent[] {
  return globSync(entry.files, { cwd }).map((file) => ({
    kind: 'inline',
    name: entry.name(fileStem(file)),
  }));
}

function compareImportSpecifiers(a: string, b: string): number {
  return a.replaceAll('/', ' ').localeCompare(b.replaceAll('/', ' '));
}

function emitHeader(entries: readonly ResolvedComponent[], runtimeImport: string): string {
  const manifestLines = entries
    .filter((entry): entry is ManifestComponent => entry.kind === 'manifest')
    .sort((a, b) => compareImportSpecifiers(a.manifestFrom, b.manifestFrom))
    .map((entry) => `import ${entry.name}Def from '${entry.manifestFrom}';`)
    .join('\n');
  const header = `// Generated by \`packages/core/scripts/generate-components.ts\`.
import { createComponent } from '${runtimeImport}';`;
  return manifestLines ? `${header}\n\n${manifestLines}` : header;
}

function manifestRef(entry: ResolvedComponent): string {
  return entry.kind === 'manifest' ? `${entry.name}Def` : `{ name: '${entry.name}' }`;
}

function emitComponents(entries: readonly ResolvedComponent[]): string {
  return entries.map((entry) => `export const ${entry.name} = createComponent(${manifestRef(entry)});`).join('\n');
}

function emitMetadata(entries: readonly ResolvedComponent[]): string {
  const lines = entries.map((entry) => `  ${entry.name}: ${manifestRef(entry)},`);
  return `export const COMPONENTS = {\n${lines.join('\n')}\n} as const;

export type Components = typeof COMPONENTS;`;
}

export async function generateComponents(
  config: ComponentsConfig,
  options: GenerateComponentsOptions = {}
): Promise<GenerateComponentsResult> {
  const { components, output, runtimeImport = '@videojs/jsx' } = config;
  const cwd = options.cwd ?? process.cwd();
  const outputAbsolute = isAbsolute(output) ? output : resolve(cwd, output);

  const resolved = components.flatMap<ResolvedComponent>((entry) =>
    typeof entry === 'string' ? resolveManifestEntry(entry, cwd, outputAbsolute) : resolveBulkEntry(entry, cwd)
  );
  const entries = resolved.sort((a, b) => a.name.localeCompare(b.name));

  if (entries.length === 0) {
    throw new Error(`No component sources matched: ${JSON.stringify(components)}`);
  }

  const duplicate = entries.find((entry, index) => entry.name === entries[index - 1]?.name);
  if (duplicate) {
    throw new Error(`Duplicate component name: ${duplicate.name}`);
  }

  const source = `${[emitHeader(entries, runtimeImport), emitComponents(entries), emitMetadata(entries)].join('\n\n')}\n`;
  const existing = existsSync(outputAbsolute) ? readFileSync(outputAbsolute, 'utf8') : null;
  const changed = existing !== source;

  if (changed && options.check) {
    throw new Error(`Generated components are stale: ${outputAbsolute}`);
  }

  if (changed) {
    mkdirSync(dirname(outputAbsolute), { recursive: true });
    writeFileSync(outputAbsolute, source, 'utf8');
  }

  return { outputPath: outputAbsolute, source, changed };
}

interface ConfigModule {
  default?: ComponentsConfig | readonly ComponentsConfig[];
  config?: ComponentsConfig | readonly ComponentsConfig[];
}

function parseArgs(argv: readonly string[]): { configPath: string; check: boolean } {
  let configPath = 'components.config.js';
  let check = false;

  for (let index = 0; index < argv.length; index++) {
    const argument = argv[index]!;
    if (argument === '--check') {
      check = true;
      continue;
    }
    if (argument === '--config' || argument === '-c') {
      const value = argv[index + 1];
      if (!value) throw new Error('Missing value for --config');
      configPath = value;
      index++;
      continue;
    }
    if (argument.startsWith('--config=')) {
      configPath = argument.slice('--config='.length);
      continue;
    }
    throw new Error(`Unknown argument: ${argument}`);
  }

  return { configPath, check };
}

async function loadConfig(configPath: string): Promise<{ configs: readonly ComponentsConfig[]; cwd: string }> {
  const absolute = isAbsolute(configPath) ? configPath : resolve(process.cwd(), configPath);
  const module = (await import(pathToFileURL(absolute).href)) as ConfigModule;
  const config = module.default ?? module.config;
  if (!config) {
    throw new Error(`Config file ${absolute} must export a default component generator config.`);
  }
  return { configs: Array.isArray(config) ? config : [config], cwd: dirname(absolute) };
}

async function runCli(): Promise<void> {
  const { configPath, check } = parseArgs(process.argv.slice(2));
  const { configs, cwd } = await loadConfig(configPath);

  for (const config of configs) {
    const result = await generateComponents(config, { cwd, check });
    process.stdout.write(`${check ? 'Verified' : 'Wrote'} ${result.outputPath}\n`);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  runCli().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
