export {
  type VjscPluginOptions,
  type VjscTransformConfig,
  type VjscTransformContext,
  type VjscTransformer,
  vjscPlugin,
} from './bundle';
export type {
  ComponentFileSet,
  ComponentSource,
  CreateSchemaModuleOptions,
  GenerateSchemaConfig,
  SchemaModule,
} from './components/generate/schema';
export { createSchemaModule } from './components/generate/schema';
export {
  type CompilerAsset,
  type CompilerConfig,
  type CompilerContext,
  type CompilerDiagnostic,
  type CompilerPipelineStep,
  type CompilerPlugin,
  type CompilerPluginEnforce,
  type CompilerSourceMap,
  type CompilerTarget,
  type CompilerTargetOptions,
  type CompilerTransform,
  type HtmlTarget,
  html,
  type JsxTarget,
  type JsxTargetOptions,
  jsx,
} from './config';
export {
  compilerDiagnosticToJsonEvent,
  DiagnosticError,
  type DiagnosticErrorDetails,
  type DiagnosticFormat,
  type DiagnosticJsonEvent,
  type DiagnosticJsonFrameLine,
  type DiagnosticLocation,
  type DiagnosticSummaryJsonEvent,
  diagnosticLocationFromNode,
  diagnosticSummaryToJsonEvent,
  type FormatDiagnosticOptions,
  fatalDiagnosticFromError,
  formatCompilerDiagnostic,
  formatCompilerDiagnosticJsonLine,
  formatDiagnosticSummaryJsonLine,
  LogLevel,
  type LogLevelName,
  mapLogLevelStringToNumber,
  mapLogLevelToString,
  shouldUseColor,
  withDiagnosticSource,
} from './diagnostics';
export { createJsxEditor, type ExtractedJsxChild, type JsxElementEdit } from './jsx/editor';
export type { SchemaEntryContext, SchemaEntryResolver } from './registry/resolve';
export {
  type ConstStatementOptions,
  type FunctionPropSpec,
  type FunctionPropsOptions,
  type FunctionSelection,
  type FunctionSiblingStatementSpec,
  type ImportOptions,
  type ImportReference,
  type InterfacePropertyContext,
  type InterfacePropertySelection,
  type InterfaceSelection,
  type JsxElementContext,
  type JsxElementReplacement,
  type JsxElementSelection,
  type JsxElementUnwrapOptions,
  type JsxHelpers,
  type JsxPropContext,
  type JsxPropInput,
  type JsxPropsSelection,
  type JsxPropsSpec,
  type JsxPropValue,
  type JsxPropValueFactory,
  type JsxSpreadPropsOptions,
  type MatchPredicate,
  type ModuleSelection,
  type RewriteCallback,
  rewrite,
  type ScopedJsxElementSelection,
  type ScopedJsxHelpers,
  type StatementHelpers,
  type StatementSpec,
  type TransformHelpers,
  type TransformStep,
  type TypeHelpers,
  type ValueArrayOptions,
  type ValueHelpers,
  type ValueReference,
  type VariableSelection,
} from './rewrite';
export { CompilerError, type TransformOptions, type TransformResult, transform } from './transform';
export type { ImportRule } from './transforms';
export type { InterfaceDeclarationOptions, InterfacePropertySpec } from './utils/declarations';
