export {
  defineVariants,
  type VariantCodec,
  type VariantModule,
  type VjscComponentSchemaOptions,
  vjscComponentSchemaPlugin,
  type EntriesOptions,
  type MetaOptions,
  type SourceEntry,
  type TransformModule,
  type VjscPluginOptions,
  vjscPlugin,
  type VjscRegistryOptions,
  vjscRegistryPlugin,
  type TransformOptions,
} from './plugins/index';
