export type {
  ComponentFileSet,
  ComponentSource,
  CreateSchemaModuleOptions,
  SchemaModule,
} from './components/schema/generate';
export { createSchemaModule } from './components/schema/generate';
export type { SchemaEntryContext, SchemaEntryResolver } from './registry/resolve';
export {
  compilerDiagnosticToJsonEvent,
  DiagnosticError,
  type DiagnosticErrorDetails,
  type DiagnosticFormat,
  type DiagnosticJsonEvent,
  type DiagnosticJsonFrameLine,
  type DiagnosticLocation,
  type DiagnosticSummaryJsonEvent,
  diagnosticLocationFromNode,
  diagnosticSummaryToJsonEvent,
  type FormatDiagnosticOptions,
  fatalDiagnosticFromError,
  formatCompilerDiagnostic,
  formatCompilerDiagnosticJsonLine,
  formatDiagnosticSummaryJsonLine,
  LogLevel,
  type LogLevelName,
  mapLogLevelStringToNumber,
  mapLogLevelToString,
  shouldUseColor,
  withDiagnosticSource,
} from './ts/diagnostics';
export { createJsxEditor, type ExtractedJsxChild, type JsxElementEdit } from './ts/jsx/editor';
export { html, type JsxPluginOptions, jsx } from './ts/jsx/plugin';
export { importsPlugin, transformPlugin } from './ts/plugins';
export {
  type ConstStatementOptions,
  type FunctionPropSpec,
  type FunctionPropsOptions,
  type FunctionSelection,
  type FunctionSiblingStatementSpec,
  type ImportOptions,
  type ImportReference,
  type InterfacePropertyContext,
  type InterfacePropertySelection,
  type InterfaceSelection,
  type JsxElementContext,
  type JsxElementReplacement,
  type JsxElementSelection,
  type JsxElementUnwrapOptions,
  type JsxHelpers,
  type JsxPropContext,
  type JsxPropInput,
  type JsxPropsSelection,
  type JsxPropsSpec,
  type JsxPropValue,
  type JsxPropValueFactory,
  type JsxSpreadPropsOptions,
  type MatchPredicate,
  type ModuleSelection,
  type RewriteCallback,
  rewrite,
  type ScopedJsxElementSelection,
  type ScopedJsxHelpers,
  type StatementHelpers,
  type StatementSpec,
  type TransformHelpers,
  type TransformStep,
  type TypeHelpers,
  type ValueArrayOptions,
  type ValueHelpers,
  type ValueReference,
  type VariableSelection,
} from './ts/rewrite';
export {
  type Compiler,
  CompilerError,
  type CompilerTransformOptions,
  createCompiler,
  type TransformOptions,
  type TransformResult,
  transform,
} from './ts/transform';
export type { ImportRule } from './ts/transforms';
export type {
  CompilerAsset,
  CompilerDiagnostic,
  CompilerModule,
  CompilerOptions,
  CompilerPlugin,
  CompilerSetupContext,
  CompilerSourceMap,
  CompilerTransform,
  CompilerTransformContext,
} from './ts/types';
export type { InterfaceDeclarationOptions, InterfacePropertySpec } from './ts/utils/declarations';
export {
  moduleFilename,
  moduleId,
  normalizeModuleId,
  normalizeResolvedId,
  type ParsedModuleId,
  parseModuleId,
} from './utils/module-id';
