name: 📄 Docs Feedback
description: Report a discrepancy in or an improvement to the docs.
labels: [triage, docs]
title: 'Docs: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Please fill this template out as completely as possible.
        * If you are not reporting a bug, but want to ask a general question, use [discussions](https://github.com/videojs/v10/discussions) instead.
        * Check the [docs](https://v10.videojs.org/docs).
        * Please check to see if there's an existing issue and replying there instead.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: packages
    attributes:
      label: Which documentation could use some work?
      multiple: true
      options:
        - Core (@videojs/core)
        - Icons (@videojs/icons)
        - HTML (@videojs/html)
        - React (@videojs/react)
        - general framework documentation
    validations:
      required: true
  - type: dropdown
    id: docs-type
    attributes:
      label: Is this a discrepancy or an improvement?
      multiple: true
      options:
        - discrepancy
        - improvement
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 🖊 Describe what you'd like to see change in the documentation
      description: Please provide a clear and concise description of what you want to see changed. If applicable, provide screenshots and/or videos.
    validations:
      required: true
  - type: textarea
    id: why-description
    attributes:
      label: 💡 Describe how you think this change will help the documentation
      description: Please provide a clear and concise description of why you think this would improve our documentation
    validations:
      required: true
