export * from './definition';
export {
  type BaseProps,
  type Component,
  type ComponentNode,
  type ComponentType,
  type CreateComponentResult,
  createComponent,
  Fragment,
  Group,
  type GroupProps,
  type JSX,
  jsx,
  jsxs,
  type Props,
  type PropsWithChildren,
  Slot,
  type SlotProps,
  Template,
  type TemplatePartProps,
  type TemplateProps,
  Text,
  type TextProps,
  VIDEOJS_NODE,
} from './jsx-runtime';
export { plugin } from './plugin';
export {
  type ComponentRegistry,
  type ComponentRegistryBinding,
  defineRegistry,
  defineTarget,
  extendRegistry,
  Host,
  type HostComponent,
  isHost,
  isTargetComponent,
  type RegistryComponentContext,
  type RegistryNode,
  type RegistryOptions,
  type RegistryPart,
  type RegistryPartCollection,
  type RegistryPrimitives,
  type RegistryRenderContext,
  type RegistryTarget,
  type RegistryTemplate,
  type RegistryTypeResolver,
  type TargetComponent,
  type TargetDefinition,
  type TargetNamedImport,
  type TargetReference,
  type TargetRenderDefinition,
  type TargetSideEffectImport,
} from './registry';
