export * from './definition';
export {
  type BaseProps,
  type ClassNameValue,
  type Component,
  type ComponentNode,
  type ComponentProps,
  type ComponentType,
  type CreateComponentResult,
  createComponent,
  Fragment,
  type FunctionComponent,
  type JSX,
  jsx,
  jsxs,
  type PropsWithChildren,
  Slot,
  type SlotProps,
  Template,
  type TemplatePartProps,
  type TemplateProps,
  Text,
  type TextProps,
  VIDEOJS_NODE,
} from './jsx-runtime';
export { plugin } from './plugin';
export {
  type ComponentRegistry,
  defineRegistry,
  defineTarget,
  Host,
  type HostComponent,
  isHost,
  isTargetComponent,
  type RegistryComponentContext,
  type RegistryNode,
  type RegistryPart,
  type RegistryPartCollection,
  type RegistryPrimitives,
  type RegistryRenderContext,
  type RegistryTemplate,
  type RegistryTemplateAttachment,
  type TargetComponent,
  type TargetDefinition,
  type TargetNamedImport,
  type TargetReference,
  type TargetRenderDefinition,
  type TargetSideEffectImport,
} from './registry';
