// AUTO-GENERATED by `@videojs/core/scripts/generate-components`. DO NOT EDIT.
import { createComponent } from '../../jsx-runtime';

import AirPlayButtonDef from './airplay-button/airplay-button-component';
import AlertDialogDef from './alert-dialog/alert-dialog-component';
import BufferingIndicatorDef from './buffering-indicator/buffering-indicator-component';
import CaptionsButtonDef from './captions-button/captions-button-component';
import CaptionsRadioGroupDef from './captions-radio-group/captions-radio-group-component';
import CastButtonDef from './cast-button/cast-button-component';
import ContainerDef from './container/container-component';
import ControlsDef from './controls/controls-component';
import ErrorDialogDef from './error-dialog/error-dialog-component';
import FeatureAvailabilityDef from './feature-availability/feature-availability-component';
import FullscreenButtonDef from './fullscreen-button/fullscreen-button-component';
import GestureDef from './gesture/gesture-component';
import HotkeyDef from './hotkey/hotkey-component';
import LiveButtonDef from './live-button/live-button-component';
import MenuDef from './menu/menu-component';
import MuteButtonDef from './mute-button/mute-button-component';
import OverlayDef from './overlay/overlay-component';
import PiPButtonDef from './pip-button/pip-button-component';
import PlayButtonDef from './play-button/play-button-component';
import PlaybackRateButtonDef from './playback-rate-button/playback-rate-button-component';
import PlaybackRateRadioGroupDef from './playback-rate-radio-group/playback-rate-radio-group-component';
import PopoverDef from './popover/popover-component';
import PosterDef from './poster/poster-component';
import QualityRadioGroupDef from './quality-radio-group/quality-radio-group-component';
import SeekButtonDef from './seek-button/seek-button-component';
import SeekIndicatorDef from './seek-indicator/seek-indicator-component';
import SliderDef from './slider/slider-component';
import StatusAnnouncerDef from './status-announcer/status-announcer-component';
import StatusIndicatorDef from './status-indicator/status-indicator-component';
import TextDef from './text/text-component';
import ThumbnailDef from './thumbnail/thumbnail-component';
import TimeDef from './time/time-component';
import TimeSliderDef from './time-slider/time-slider-component';
import TooltipDef from './tooltip/tooltip-component';
import VolumeIndicatorDef from './volume-indicator/volume-indicator-component';
import VolumeSliderDef from './volume-slider/volume-slider-component';

export const AirPlayButton = createComponent(AirPlayButtonDef);
export const AlertDialog = createComponent(AlertDialogDef);
export const BufferingIndicator = createComponent(BufferingIndicatorDef);
export const CaptionsButton = createComponent(CaptionsButtonDef);
export const CaptionsRadioGroup = createComponent(CaptionsRadioGroupDef);
export const CastButton = createComponent(CastButtonDef);
export const Container = createComponent(ContainerDef);
export const Controls = createComponent(ControlsDef);
export const ErrorDialog = createComponent(ErrorDialogDef);
export const FeatureAvailability = createComponent(FeatureAvailabilityDef);
export const FullscreenButton = createComponent(FullscreenButtonDef);
export const Gesture = createComponent(GestureDef);
export const Hotkey = createComponent(HotkeyDef);
export const LiveButton = createComponent(LiveButtonDef);
export const Menu = createComponent(MenuDef);
export const MuteButton = createComponent(MuteButtonDef);
export const Overlay = createComponent(OverlayDef);
export const PiPButton = createComponent(PiPButtonDef);
export const PlaybackRateButton = createComponent(PlaybackRateButtonDef);
export const PlaybackRateRadioGroup = createComponent(PlaybackRateRadioGroupDef);
export const PlayButton = createComponent(PlayButtonDef);
export const Popover = createComponent(PopoverDef);
export const Poster = createComponent(PosterDef);
export const QualityRadioGroup = createComponent(QualityRadioGroupDef);
export const SeekButton = createComponent(SeekButtonDef);
export const SeekIndicator = createComponent(SeekIndicatorDef);
export const Slider = createComponent(SliderDef);
export const StatusAnnouncer = createComponent(StatusAnnouncerDef);
export const StatusIndicator = createComponent(StatusIndicatorDef);
export const Text = createComponent(TextDef);
export const Thumbnail = createComponent(ThumbnailDef);
export const Time = createComponent(TimeDef);
export const TimeSlider = createComponent(TimeSliderDef);
export const Tooltip = createComponent(TooltipDef);
export const VolumeIndicator = createComponent(VolumeIndicatorDef);
export const VolumeSlider = createComponent(VolumeSliderDef);

export const COMPONENTS = {
  AirPlayButton: AirPlayButtonDef,
  AlertDialog: AlertDialogDef,
  BufferingIndicator: BufferingIndicatorDef,
  CaptionsButton: CaptionsButtonDef,
  CaptionsRadioGroup: CaptionsRadioGroupDef,
  CastButton: CastButtonDef,
  Container: ContainerDef,
  Controls: ControlsDef,
  ErrorDialog: ErrorDialogDef,
  FeatureAvailability: FeatureAvailabilityDef,
  FullscreenButton: FullscreenButtonDef,
  Gesture: GestureDef,
  Hotkey: HotkeyDef,
  LiveButton: LiveButtonDef,
  Menu: MenuDef,
  MuteButton: MuteButtonDef,
  Overlay: OverlayDef,
  PiPButton: PiPButtonDef,
  PlaybackRateButton: PlaybackRateButtonDef,
  PlaybackRateRadioGroup: PlaybackRateRadioGroupDef,
  PlayButton: PlayButtonDef,
  Popover: PopoverDef,
  Poster: PosterDef,
  QualityRadioGroup: QualityRadioGroupDef,
  SeekButton: SeekButtonDef,
  SeekIndicator: SeekIndicatorDef,
  Slider: SliderDef,
  StatusAnnouncer: StatusAnnouncerDef,
  StatusIndicator: StatusIndicatorDef,
  Text: TextDef,
  Thumbnail: ThumbnailDef,
  Time: TimeDef,
  TimeSlider: TimeSliderDef,
  Tooltip: TooltipDef,
  VolumeIndicator: VolumeIndicatorDef,
  VolumeSlider: VolumeSliderDef,
} as const;

export type Components = typeof COMPONENTS;
