// Generated by `packages/core/scripts/generate-components.ts`.
import { createComponent } from '@videojs/jsx';

import AirPlayButtonDef from './airplay-button/airplay-button-component';
import BufferingIndicatorDef from './buffering-indicator/buffering-indicator-component';
import CaptionsButtonDef from './captions-button/captions-button-component';
import CastButtonDef from './cast-button/cast-button-component';
import ContainerDef from './container/container-component';
import ControlsDef from './controls/controls-component';
import ErrorDialogDef from './error-dialog/error-dialog-component';
import FullscreenButtonDef from './fullscreen-button/fullscreen-button-component';
import MuteButtonDef from './mute-button/mute-button-component';
import PiPButtonDef from './pip-button/pip-button-component';
import PlayButtonDef from './play-button/play-button-component';
import PopoverDef from './popover/popover-component';
import PosterDef from './poster/poster-component';
import SeekButtonDef from './seek-button/seek-button-component';
import SliderDef from './slider/slider-component';
import TextDef from './text/text-component';
import TimeDef from './time/time-component';
import TimeSliderDef from './time-slider/time-slider-component';
import TooltipDef from './tooltip/tooltip-component';
import VolumeSliderDef from './volume-slider/volume-slider-component';

export const AirPlayButton = createComponent(AirPlayButtonDef);
export const BufferingIndicator = createComponent(BufferingIndicatorDef);
export const CaptionsButton = createComponent(CaptionsButtonDef);
export const CastButton = createComponent(CastButtonDef);
export const Container = createComponent(ContainerDef);
export const Controls = createComponent(ControlsDef);
export const ErrorDialog = createComponent(ErrorDialogDef);
export const FullscreenButton = createComponent(FullscreenButtonDef);
export const MuteButton = createComponent(MuteButtonDef);
export const PiPButton = createComponent(PiPButtonDef);
export const PlayButton = createComponent(PlayButtonDef);
export const Popover = createComponent(PopoverDef);
export const Poster = createComponent(PosterDef);
export const SeekButton = createComponent(SeekButtonDef);
export const Slider = createComponent(SliderDef);
export const Text = createComponent(TextDef);
export const Time = createComponent(TimeDef);
export const TimeSlider = createComponent(TimeSliderDef);
export const Tooltip = createComponent(TooltipDef);
export const VolumeSlider = createComponent(VolumeSliderDef);

export const COMPONENTS = {
  AirPlayButton: AirPlayButtonDef,
  BufferingIndicator: BufferingIndicatorDef,
  CaptionsButton: CaptionsButtonDef,
  CastButton: CastButtonDef,
  Container: ContainerDef,
  Controls: ControlsDef,
  ErrorDialog: ErrorDialogDef,
  FullscreenButton: FullscreenButtonDef,
  MuteButton: MuteButtonDef,
  PiPButton: PiPButtonDef,
  PlayButton: PlayButtonDef,
  Popover: PopoverDef,
  Poster: PosterDef,
  SeekButton: SeekButtonDef,
  Slider: SliderDef,
  Text: TextDef,
  Time: TimeDef,
  TimeSlider: TimeSliderDef,
  Tooltip: TooltipDef,
  VolumeSlider: VolumeSliderDef,
} as const;

export type Components = typeof COMPONENTS;
