// Generated by `packages/core/scripts/generate-components.ts`.
import { createComponent } from '@videojs/jsx';

import ControlsDef from './controls/controls-component';
import FullscreenButtonDef from './fullscreen-button/fullscreen-button-component';
import MuteButtonDef from './mute-button/mute-button-component';
import PlayButtonDef from './play-button/play-button-component';
import PopoverDef from './popover/popover-component';
import SeekButtonDef from './seek-button/seek-button-component';
import SliderDef from './slider/slider-component';
import TextDef from './text/text-component';
import TimeDef from './time/time-component';
import TimeSliderDef from './time-slider/time-slider-component';
import TooltipDef from './tooltip/tooltip-component';
import VolumeSliderDef from './volume-slider/volume-slider-component';

export const Controls = createComponent(ControlsDef);
export const FullscreenButton = createComponent(FullscreenButtonDef);
export const MuteButton = createComponent(MuteButtonDef);
export const PlayButton = createComponent(PlayButtonDef);
export const Popover = createComponent(PopoverDef);
export const SeekButton = createComponent(SeekButtonDef);
export const Slider = createComponent(SliderDef);
export const Text = createComponent(TextDef);
export const Time = createComponent(TimeDef);
export const TimeSlider = createComponent(TimeSliderDef);
export const Tooltip = createComponent(TooltipDef);
export const VolumeSlider = createComponent(VolumeSliderDef);

export const COMPONENTS = {
  Controls: ControlsDef,
  FullscreenButton: FullscreenButtonDef,
  MuteButton: MuteButtonDef,
  PlayButton: PlayButtonDef,
  Popover: PopoverDef,
  SeekButton: SeekButtonDef,
  Slider: SliderDef,
  Text: TextDef,
  Time: TimeDef,
  TimeSlider: TimeSliderDef,
  Tooltip: TooltipDef,
  VolumeSlider: VolumeSliderDef,
} as const;

export type Components = typeof COMPONENTS;
