// Generated by `vjsc generate`.
import { defineTarget } from '@videojs/compiler/components';

export const AirPlayButton = defineTarget({
  tagName: 'media-airplay-button',
  import: {
    from: '@videojs/html/ui/airplay-button',
    sideEffect: true,
  },
});

export const AlertDialog = defineTarget({
  tagName: 'media-alert-dialog',
  import: {
    from: '@videojs/html/ui/alert-dialog',
    sideEffect: true,
  },
});

export const AlertDialogClose = defineTarget({
  tagName: 'media-alert-dialog-close',
  import: {
    from: '@videojs/html/ui/alert-dialog-close',
    sideEffect: true,
  },
});

export const AlertDialogDescription = defineTarget({
  tagName: 'media-alert-dialog-description',
  import: {
    from: '@videojs/html/ui/alert-dialog-description',
    sideEffect: true,
  },
});

export const AlertDialogTitle = defineTarget({
  tagName: 'media-alert-dialog-title',
  import: {
    from: '@videojs/html/ui/alert-dialog-title',
    sideEffect: true,
  },
});

export const AudioTrackRadioGroup = defineTarget({
  tagName: 'media-audio-track-radio-group',
  import: {
    from: '@videojs/html/ui/audio-track-radio-group',
    sideEffect: true,
  },
});

export const BackgroundVideo = defineTarget({
  tagName: 'background-video',
  import: {
    from: '@videojs/html/media/background-video',
    sideEffect: true,
  },
});

export const BufferingIndicator = defineTarget({
  tagName: 'media-buffering-indicator',
  import: {
    from: '@videojs/html/ui/buffering-indicator',
    sideEffect: true,
  },
});

export const CaptionsButton = defineTarget({
  tagName: 'media-captions-button',
  import: {
    from: '@videojs/html/ui/captions-button',
    sideEffect: true,
  },
});

export const CaptionsRadioGroup = defineTarget({
  tagName: 'media-captions-radio-group',
  import: {
    from: '@videojs/html/ui/captions-radio-group',
    sideEffect: true,
  },
});

export const CastButton = defineTarget({
  tagName: 'media-cast-button',
  import: {
    from: '@videojs/html/ui/cast-button',
    sideEffect: true,
  },
});

export const Controls = defineTarget({
  tagName: 'media-controls',
  import: {
    from: '@videojs/html/ui/controls',
    sideEffect: true,
  },
});

export const ControlsGroup = defineTarget({
  tagName: 'media-controls-group',
  import: {
    from: '@videojs/html/ui/controls-group',
    sideEffect: true,
  },
});

export const DashVideo = defineTarget({
  tagName: 'dash-video',
  import: {
    from: '@videojs/html/media/dash-video',
    sideEffect: true,
  },
});

export const ErrorDialog = defineTarget({
  tagName: 'media-error-dialog',
  import: {
    from: '@videojs/html/ui/error-dialog',
    sideEffect: true,
  },
});

export const FullscreenButton = defineTarget({
  tagName: 'media-fullscreen-button',
  import: {
    from: '@videojs/html/ui/fullscreen-button',
    sideEffect: true,
  },
});

export const Gesture = defineTarget({
  tagName: 'media-gesture',
  import: {
    from: '@videojs/html/ui/gesture',
    sideEffect: true,
  },
});

export const HlsAudio = defineTarget({
  tagName: 'hls-audio',
  import: {
    from: '@videojs/html/media/hls-audio',
    sideEffect: true,
  },
});

export const HlsBackgroundVideo = defineTarget({
  tagName: 'hls-background-video',
  import: {
    from: '@videojs/html/media/hls-background-video',
    sideEffect: true,
  },
});

export const HlsJsVideo = defineTarget({
  tagName: 'hlsjs-video',
  import: {
    from: '@videojs/html/media/hlsjs-video',
    sideEffect: true,
  },
});

export const HlsVideo = defineTarget({
  tagName: 'hls-video',
  import: {
    from: '@videojs/html/media/hls-video',
    sideEffect: true,
  },
});

export const Hotkey = defineTarget({
  tagName: 'media-hotkey',
  import: {
    from: '@videojs/html/ui/hotkey',
    sideEffect: true,
  },
});

export const I18nProvider = defineTarget({
  tagName: 'media-i18n',
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
});

export const MediaContainer = defineTarget({
  tagName: 'media-container',
  import: {
    from: '@videojs/html/media/container',
    sideEffect: true,
  },
});

export const Menu = defineTarget({
  tagName: 'media-menu',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuCheckboxItem = defineTarget({
  tagName: 'media-menu-checkbox-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuGroup = defineTarget({
  tagName: 'media-menu-group',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuGroupLabel = defineTarget({
  tagName: 'media-menu-group-label',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuItem = defineTarget({
  tagName: 'media-menu-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuItemIndicator = defineTarget({
  tagName: 'media-menu-item-indicator',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuRadioGroup = defineTarget({
  tagName: 'media-menu-radio-group',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuRadioItem = defineTarget({
  tagName: 'media-menu-radio-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuSeparator = defineTarget({
  tagName: 'media-menu-separator',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MuteButton = defineTarget({
  tagName: 'media-mute-button',
  import: {
    from: '@videojs/html/ui/mute-button',
    sideEffect: true,
  },
});

export const MuxBackgroundVideo = defineTarget({
  tagName: 'mux-background-video',
  import: {
    from: '@videojs/html/media/mux-background-video',
    sideEffect: true,
  },
});

export const NativeHlsVideo = defineTarget({
  tagName: 'native-hls-video',
  import: {
    from: '@videojs/html/media/native-hls-video',
    sideEffect: true,
  },
});

export const PiPButton = defineTarget({
  tagName: 'media-pip-button',
  import: {
    from: '@videojs/html/ui/pip-button',
    sideEffect: true,
  },
});

export const PlaybackRateButton = defineTarget({
  tagName: 'media-playback-rate-button',
  import: {
    from: '@videojs/html/ui/playback-rate-button',
    sideEffect: true,
  },
});

export const PlaybackRateRadioGroup = defineTarget({
  tagName: 'media-playback-rate-radio-group',
  import: {
    from: '@videojs/html/ui/playback-rate-radio-group',
    sideEffect: true,
  },
});

export const PlayButton = defineTarget({
  tagName: 'media-play-button',
  import: {
    from: '@videojs/html/ui/play-button',
    sideEffect: true,
  },
});

export const Popover = defineTarget({
  tagName: 'media-popover',
  import: {
    from: '@videojs/html/ui/popover',
    sideEffect: true,
  },
});

export const Poster = defineTarget({
  tagName: 'media-poster',
  import: {
    from: '@videojs/html/ui/poster',
    sideEffect: true,
  },
});

export const QualityRadioGroup = defineTarget({
  tagName: 'media-quality-radio-group',
  import: {
    from: '@videojs/html/ui/quality-radio-group',
    sideEffect: true,
  },
});

export const SeekButton = defineTarget({
  tagName: 'media-seek-button',
  import: {
    from: '@videojs/html/ui/seek-button',
    sideEffect: true,
  },
});

export const SeekIndicator = defineTarget({
  tagName: 'media-seek-indicator',
  import: {
    from: '@videojs/html/ui/seek-indicator',
    sideEffect: true,
  },
});

export const SeekIndicatorValue = defineTarget({
  tagName: 'media-seek-indicator-value',
  import: {
    from: '@videojs/html/ui/seek-indicator-value',
    sideEffect: true,
  },
});

export const Slider = defineTarget({
  tagName: 'media-slider',
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
});

export const SliderBuffer = defineTarget({
  tagName: 'media-slider-buffer',
  import: {
    from: '@videojs/html/ui/slider-buffer',
    sideEffect: true,
  },
});

export const SliderFill = defineTarget({
  tagName: 'media-slider-fill',
  import: {
    from: '@videojs/html/ui/slider-fill',
    sideEffect: true,
  },
});

export const SliderPreview = defineTarget({
  tagName: 'media-slider-preview',
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
});

export const SliderThumb = defineTarget({
  tagName: 'media-slider-thumb',
  import: {
    from: '@videojs/html/ui/slider-thumb',
    sideEffect: true,
  },
});

export const SliderThumbnail = defineTarget({
  tagName: 'media-slider-thumbnail',
  import: {
    from: '@videojs/html/ui/slider-thumbnail',
    sideEffect: true,
  },
});

export const SliderTrack = defineTarget({
  tagName: 'media-slider-track',
  import: {
    from: '@videojs/html/ui/slider-track',
    sideEffect: true,
  },
});

export const SliderValue = defineTarget({
  tagName: 'media-slider-value',
  import: {
    from: '@videojs/html/ui/slider-value',
    sideEffect: true,
  },
});

export const StatusAnnouncer = defineTarget({
  tagName: 'media-status-announcer',
  import: {
    from: '@videojs/html/ui/status-announcer',
    sideEffect: true,
  },
});

export const StatusIndicator = defineTarget({
  tagName: 'media-status-indicator',
  import: {
    from: '@videojs/html/ui/status-indicator',
    sideEffect: true,
  },
});

export const StatusIndicatorValue = defineTarget({
  tagName: 'media-status-indicator-value',
  import: {
    from: '@videojs/html/ui/status-indicator-value',
    sideEffect: true,
  },
});

export const Text = defineTarget({
  tagName: 'media-text',
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
});

export const Thumbnail = defineTarget({
  tagName: 'media-thumbnail',
  import: {
    from: '@videojs/html/ui/thumbnail',
    sideEffect: true,
  },
});

export const Time = defineTarget({
  tagName: 'media-time',
  import: {
    from: '@videojs/html/ui/time',
    sideEffect: true,
  },
});

export const TimeGroup = defineTarget({
  tagName: 'media-time-group',
  import: {
    from: '@videojs/html/ui/time-group',
    sideEffect: true,
  },
});

export const TimeSeparator = defineTarget({
  tagName: 'media-time-separator',
  import: {
    from: '@videojs/html/ui/time-separator',
    sideEffect: true,
  },
});

export const TimeSlider = defineTarget({
  tagName: 'media-time-slider',
  import: {
    from: '@videojs/html/ui/time-slider',
    sideEffect: true,
  },
});

export const TimeSliderChapters = defineTarget({
  tagName: 'media-time-slider-chapters',
  import: {
    from: '@videojs/html/ui/time-slider-chapters',
    sideEffect: true,
  },
});

export const TimeSliderChapterTitle = defineTarget({
  tagName: 'media-time-slider-chapter-title',
  import: {
    from: '@videojs/html/ui/time-slider-chapter-title',
    sideEffect: true,
  },
});

export const Tooltip = defineTarget({
  tagName: 'media-tooltip',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const TooltipGroup = defineTarget({
  tagName: 'media-tooltip-group',
  import: {
    from: '@videojs/html/ui/tooltip-group',
    sideEffect: true,
  },
});

export const TooltipLabel = defineTarget({
  tagName: 'media-tooltip-label',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const TooltipShortcut = defineTarget({
  tagName: 'media-tooltip-shortcut',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const VimeoVideo = defineTarget({
  tagName: 'vimeo-video',
  import: {
    from: '@videojs/html/media/vimeo-video',
    sideEffect: true,
  },
});

export const VolumeIndicator = defineTarget({
  tagName: 'media-volume-indicator',
  import: {
    from: '@videojs/html/ui/volume-indicator',
    sideEffect: true,
  },
});

export const VolumeIndicatorFill = defineTarget({
  tagName: 'media-volume-indicator-fill',
  import: {
    from: '@videojs/html/ui/volume-indicator-fill',
    sideEffect: true,
  },
});

export const VolumeIndicatorValue = defineTarget({
  tagName: 'media-volume-indicator-value',
  import: {
    from: '@videojs/html/ui/volume-indicator-value',
    sideEffect: true,
  },
});

export const VolumeSlider = defineTarget({
  tagName: 'media-volume-slider',
  import: {
    from: '@videojs/html/ui/volume-slider',
    sideEffect: true,
  },
});

export const YouTubeVideo = defineTarget({
  tagName: 'youtube-video',
  import: {
    from: '@videojs/html/media/youtube-video',
    sideEffect: true,
  },
});

export const targets = {
  AirPlayButton,
  AlertDialog,
  AlertDialogClose,
  AlertDialogDescription,
  AlertDialogTitle,
  AudioTrackRadioGroup,
  BackgroundVideo,
  BufferingIndicator,
  CaptionsButton,
  CaptionsRadioGroup,
  CastButton,
  Controls,
  ControlsGroup,
  DashVideo,
  ErrorDialog,
  FullscreenButton,
  Gesture,
  HlsAudio,
  HlsBackgroundVideo,
  HlsJsVideo,
  HlsVideo,
  Hotkey,
  I18nProvider,
  MediaContainer,
  Menu,
  MenuCheckboxItem,
  MenuGroup,
  MenuGroupLabel,
  MenuItem,
  MenuItemIndicator,
  MenuRadioGroup,
  MenuRadioItem,
  MenuSeparator,
  MuteButton,
  MuxBackgroundVideo,
  NativeHlsVideo,
  PiPButton,
  PlaybackRateButton,
  PlaybackRateRadioGroup,
  PlayButton,
  Popover,
  Poster,
  QualityRadioGroup,
  SeekButton,
  SeekIndicator,
  SeekIndicatorValue,
  Slider,
  SliderBuffer,
  SliderFill,
  SliderPreview,
  SliderThumb,
  SliderThumbnail,
  SliderTrack,
  SliderValue,
  StatusAnnouncer,
  StatusIndicator,
  StatusIndicatorValue,
  Text,
  Thumbnail,
  Time,
  TimeGroup,
  TimeSeparator,
  TimeSlider,
  TimeSliderChapters,
  TimeSliderChapterTitle,
  Tooltip,
  TooltipGroup,
  TooltipLabel,
  TooltipShortcut,
  VimeoVideo,
  VolumeIndicator,
  VolumeIndicatorFill,
  VolumeIndicatorValue,
  VolumeSlider,
  YouTubeVideo,
} as const;
