import { globSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig } from 'vite-plus';
import type { UserConfig as PackUserConfig } from 'vite-plus/pack';

import { isDevBuildMode, type PackageBuildMode, packageBuildConfig, packageBuildModes } from '../../build/pack.ts';
import { copyCssPlugin } from '../../build/plugins/copy-css-plugin.ts';
import { cachedTaskInputs, packageTestTask, workspaceTaskDependencies } from '../../build/task.ts';
import { HTML_DIR } from './scripts/html-entries.ts';

const packageDir = dirname(fileURLToPath(import.meta.url));
const htmlDistDir = fileURLToPath(new URL('../html/dist/default', import.meta.url));

// Generated by scripts/generate-html-entries.ts, which the build task runs first.
const htmlEntries = Object.fromEntries(
  globSync(`src/${HTML_DIR}/**/*.ts`, { cwd: packageDir }).map((file) => [
    file.replace(/^src\//, '').replace(/\.ts$/, ''),
    file,
  ])
);

const createPackConfig = (mode: PackageBuildMode): PackUserConfig => ({
  ...packageBuildConfig(mode, 'browser'),
  entry: {
    index: './src/index.ts',
    'errors/index': './src/errors/index.ts',
    ...htmlEntries,
  },
  treeshake: {
    // Re-exports of define/* modules exist for their registration side effects.
    moduleSideEffects: [{ test: new RegExp(`/${HTML_DIR}/define/`), sideEffects: true }],
  },
  plugins: isDevBuildMode(mode)
    ? []
    : [
        // `@videojs/html` serves every stylesheet from dist/default, so the mirror only needs them there.
        copyCssPlugin({
          outDir: `dist/${mode}`,
          rootDir: htmlDistDir,
          pattern: 'define/**/*.css',
          inline: false,
          rename: (file) => `${HTML_DIR}/${file}`,
        }),
        copyCssPlugin({
          outDir: 'dist',
          pattern: 'src/legacy/video-js.css',
          inline: false,
          rename: () => 'video-js.css',
        }),
      ],
});

export default defineConfig({
  run: {
    tasks: {
      build: {
        command: 'node --import tsx ./scripts/generate-html-entries.ts && vp pack',
        dependsOn: workspaceTaskDependencies(),
        input: cachedTaskInputs,
        output: ['dist/**', `src/${HTML_DIR}/**`],
      },
      'test:ci': packageTestTask(),
    },
  },
  define: {
    __DEV__: 'true',
  },
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'video.js',
          include: ['src/**/*.test.ts'],
          // The root entry re-exports `@videojs/html`, whose custom elements need a DOM to load.
          environment: 'happy-dom',
        },
      },
      {
        extends: true,
        test: {
          name: 'video.js/scripts',
          include: ['scripts/**/*.test.ts'],
        },
      },
    ],
  },
  pack: packageBuildModes.map(createPackConfig),
});
