import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, isAbsolute, relative, resolve } from 'node:path';
import ts from 'typescript';

import type { BulkComponentEntry, CompilerConfig } from './config';

interface ManifestComponent {
  kind: 'manifest';
  name: string;
  /** Module specifier (relative to output) for `import XDef from '...'`. */
  manifestFrom: string;
}

interface InlineComponent {
  kind: 'inline';
  name: string;
}

type ResolvedComponent = ManifestComponent | InlineComponent;

function isDefineComponentCall(node: ts.Node): node is ts.CallExpression {
  if (!ts.isCallExpression(node)) return false;
  const callee = node.expression;
  if (ts.isIdentifier(callee) && callee.text === 'defineComponent') return true;
  // Curried form: defineComponent<P>()(...) — outer call's expression is the inner call.
  return (
    ts.isCallExpression(callee) && ts.isIdentifier(callee.expression) && callee.expression.text === 'defineComponent'
  );
}

function findDefaultExportCall(sourceFile: ts.SourceFile): ts.CallExpression | null {
  for (const stmt of sourceFile.statements) {
    if (!ts.isExportAssignment(stmt) || stmt.isExportEquals) continue;
    if (isDefineComponentCall(stmt.expression)) return stmt.expression;
  }
  return null;
}

function parseComponentName(manifestPath: string): string {
  const sourceText = readFileSync(manifestPath, 'utf8');
  const sourceFile = ts.createSourceFile(manifestPath, sourceText, ts.ScriptTarget.Latest, true);
  const call = findDefaultExportCall(sourceFile);
  if (!call) {
    throw new Error(`No \`export default defineComponent(...)\` found in ${manifestPath}`);
  }
  const arg = call.arguments[0];
  if (!arg || !ts.isObjectLiteralExpression(arg)) {
    throw new Error(`defineComponent() in ${manifestPath} must take an object literal`);
  }
  for (const prop of arg.properties) {
    if (
      ts.isPropertyAssignment(prop) &&
      ts.isIdentifier(prop.name) &&
      prop.name.text === 'name' &&
      ts.isStringLiteral(prop.initializer)
    ) {
      return prop.initializer.text;
    }
  }
  throw new Error(`defineComponent() in ${manifestPath} is missing a literal \`name:\` field`);
}

function manifestPathToImport(manifestPath: string, outputFile: string): string {
  let rel = relative(dirname(outputFile), manifestPath);
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel.replace(/\.ts$/, '');
}

function fileStem(filePath: string): string {
  const base = basename(filePath);
  const ext = extname(base);
  return ext ? base.slice(0, -ext.length) : base;
}

function resolveManifestEntry(pattern: string, cwd: string, outputAbsolute: string): ManifestComponent[] {
  const matches = globSync(pattern, { cwd }).map((p) => (isAbsolute(p) ? p : resolve(cwd, p)));
  return matches.map((manifestPath) => ({
    kind: 'manifest',
    name: parseComponentName(manifestPath),
    manifestFrom: manifestPathToImport(manifestPath, outputAbsolute),
  }));
}

function resolveBulkEntry(entry: BulkComponentEntry, cwd: string): InlineComponent[] {
  const matches = globSync(entry.files, { cwd });
  return matches.map((file) => ({
    kind: 'inline',
    name: entry.name(fileStem(file)),
  }));
}

function emitHeader(entries: readonly ResolvedComponent[]): string {
  const manifestLines = entries
    .filter((e): e is ManifestComponent => e.kind === 'manifest')
    .sort((a, b) => compareImportSpecifiers(a.manifestFrom, b.manifestFrom))
    .map((e) => `import ${e.name}Def from '${e.manifestFrom}';`)
    .join('\n');
  const head = `// AUTO-GENERATED by \`@videojs/compiler\`. DO NOT EDIT.
import { createComponent } from '@videojs/compiler/jsx-runtime';`;
  return manifestLines ? `${head}\n\n${manifestLines}` : head;
}

function manifestRef(entry: ResolvedComponent): string {
  return entry.kind === 'manifest' ? `${entry.name}Def` : `{ name: '${entry.name}' }`;
}

function compareImportSpecifiers(a: string, b: string): number {
  const aKey = a.replaceAll('/', ' ');
  const bKey = b.replaceAll('/', ' ');
  if (aKey < bKey) return -1;
  if (aKey > bKey) return 1;
  return 0;
}

function emitComponents(entries: readonly ResolvedComponent[]): string {
  return entries.map((e) => `export const ${e.name} = createComponent(${manifestRef(e)});`).join('\n');
}

function emitMetadata(entries: readonly ResolvedComponent[]): string {
  const lines = entries.map((e) => `  ${e.name}: ${manifestRef(e)},`);
  return `export const COMPONENTS = {\n${lines.join('\n')}\n} as const;

export type Components = typeof COMPONENTS;`;
}

export interface GenerateResult {
  outputPath: string;
  source: string;
}

export async function generate(config: CompilerConfig): Promise<GenerateResult> {
  if (!config.generate) {
    throw new Error('@videojs/compiler: generate() requires a `generate` field in the compiler config');
  }

  const { components, output } = config.generate;
  const cwd = process.cwd();
  const outputAbsolute = isAbsolute(output) ? output : resolve(cwd, output);

  const resolved: ResolvedComponent[] = components.flatMap<ResolvedComponent>((entry) =>
    typeof entry === 'string' ? resolveManifestEntry(entry, cwd, outputAbsolute) : resolveBulkEntry(entry, cwd)
  );
  const entries = resolved.sort((a, b) => a.name.localeCompare(b.name));

  if (entries.length === 0) {
    throw new Error(`No component sources matched: ${JSON.stringify(components)}`);
  }

  const source = `${[emitHeader(entries), emitComponents(entries), emitMetadata(entries)].join('\n\n')}\n`;
  // Skip the write when contents are unchanged so watch-mode rebuilds don't
  // re-trigger themselves.
  const existing = existsSync(outputAbsolute) ? readFileSync(outputAbsolute, 'utf8') : null;

  if (existing !== source) {
    writeFileSync(outputAbsolute, source, 'utf8');
  }

  return { outputPath: outputAbsolute, source };
}
