export { type CompileOptions, type CompileResult, CompilerError, compile } from './compile';
export {
  type CompilerAsset,
  type CompilerConfig,
  type CompilerContext,
  type CompilerDiagnostic,
  type CompilerInput,
  type CompilerOutputOptions,
  type CompilerPipelineStep,
  type CompilerPlugin,
  type CompilerPluginEnforce,
  type CompilerTarget,
  type CompilerTransform,
  defineConfig,
} from './config';
export {
  compilerDiagnosticToJsonEvent,
  DiagnosticError,
  type DiagnosticErrorDetails,
  type DiagnosticFormat,
  type DiagnosticJsonEvent,
  type DiagnosticJsonFrameLine,
  type DiagnosticLocation,
  type DiagnosticSummaryJsonEvent,
  diagnosticLocationFromNode,
  diagnosticSummaryToJsonEvent,
  type FormatDiagnosticOptions,
  fatalDiagnosticFromError,
  formatCompilerDiagnostic,
  formatCompilerDiagnosticJsonLine,
  formatDiagnosticSummaryJsonLine,
  LogLevel,
  type LogLevelName,
  mapLogLevelStringToNumber,
  mapLogLevelToString,
  shouldUseColor,
  withDiagnosticSource,
} from './diagnostics';
export {
  type AddPropImportRef,
  type AddPropOptions,
  accessPath,
  addProp,
  anyTag,
  byTag,
  type ChildAsPropOptions,
  childAsProp,
  hasChild,
  type JsxChildReplacement,
  type JsxElementLike,
  type JsxTargetOptions,
  jsx,
  jsxExpression,
  type Matcher,
  propertyAccess,
  type ReplaceJsxChildOptions,
  type ReplaceOptions,
  readStringAttribute,
  replace,
  replaceJsxChild,
  tagName,
  type WrapOptions,
  wrap,
} from './jsx';
export {
  type CompileProjectOptions,
  type CompileProjectResult,
  compileProject,
  type ProjectOutputFile,
} from './project';
export {
  type AnalyzeStylesOptions,
  analyzeStyles,
  type StyleAttributeInfo,
  type StyleSegment,
  type StyleVisitor,
  type StyleVisitorResult,
} from './styles';
export {
  type ConstStatementOptions,
  type FunctionPropSpec,
  type FunctionSelection,
  type ImportOptions,
  type ImportReference,
  type InterfacePropertyContext,
  type InterfacePropertySelection,
  type InterfaceSelection,
  type JsxElementContext,
  type JsxElementReplacement,
  type JsxElementSelection,
  type JsxHelpers,
  type JsxPropContext,
  type JsxPropsSelection,
  type JsxPropsSpec,
  type JsxPropValue,
  type MatchPredicate,
  type ModuleSelection,
  type StatementHelpers,
  type StatementSpec,
  type TransformCallback,
  type TransformHelpers,
  type TransformOptions,
  type TransformStep,
  type TypeHelpers,
  transform,
  type ValueArrayOptions,
  type ValueHelpers,
  type ValueReference,
} from './transform';
export {
  type AddImportContext,
  type AddImportRef,
  addNamedImport,
  dropUnusedImports,
  dropUnusedLocals,
  type ImportRef,
  type ImportRewriteOptions,
  type ImportRule,
  resolveRelative,
  transformImports,
} from './transforms';
