export { type CompileOptions, type CompileResult, CompilerError, compile } from './compile';
export {
  type CompilerAsset,
  type CompilerConfig,
  type CompilerContext,
  type CompilerDiagnostic,
  type CompilerInput,
  type CompilerOutputOptions,
  type CompilerPipelineStep,
  type CompilerPlugin,
  type CompilerPluginEnforce,
  type CompilerProjectConfig,
  type CompilerSourceMap,
  type CompilerTarget,
  type CompilerTransform,
  defineConfig,
  type JsxTargetOptions,
  jsx,
} from './config';
export {
  compilerDiagnosticToJsonEvent,
  DiagnosticError,
  type DiagnosticErrorDetails,
  type DiagnosticFormat,
  type DiagnosticJsonEvent,
  type DiagnosticJsonFrameLine,
  type DiagnosticLocation,
  type DiagnosticSummaryJsonEvent,
  diagnosticLocationFromNode,
  diagnosticSummaryToJsonEvent,
  type FormatDiagnosticOptions,
  fatalDiagnosticFromError,
  formatCompilerDiagnostic,
  formatCompilerDiagnosticJsonLine,
  formatDiagnosticSummaryJsonLine,
  LogLevel,
  type LogLevelName,
  mapLogLevelStringToNumber,
  mapLogLevelToString,
  shouldUseColor,
  withDiagnosticSource,
} from './diagnostics';
export {
  CONFIG_FILENAMES,
  findConfig,
  type LoadedCompilerConfig,
  type LoadedCompilerProjectConfig,
  loadConfig,
  loadConfigFile,
  loadProjectConfig,
  loadProjectConfigFile,
} from './load-config';
export {
  type CompileProjectOptions,
  type CompileProjectResult,
  compileProject,
  type ProjectOutputFile,
} from './project';
export {
  type ConstStatementOptions,
  type FunctionPropSpec,
  type FunctionSelection,
  type ImportOptions,
  type ImportReference,
  type InterfacePropertyContext,
  type InterfacePropertySelection,
  type InterfaceSelection,
  type JsxElementContext,
  type JsxElementReplacement,
  type JsxElementSelection,
  type JsxHelpers,
  type JsxPropContext,
  type JsxPropsSelection,
  type JsxPropsSpec,
  type JsxPropValue,
  type MatchPredicate,
  type ModuleSelection,
  type StatementHelpers,
  type StatementSpec,
  type TransformCallback,
  type TransformHelpers,
  type TransformOptions,
  type TransformStep,
  type TypeHelpers,
  transform,
  type ValueArrayOptions,
  type ValueHelpers,
  type ValueReference,
} from './transform';
export type { ImportRule } from './transforms';
