import { defineStyles } from '../define';

export default defineStyles({
  role: 'container',
  styles: {
    container: [
      'relative isolate block h-full w-full overflow-hidden rounded-[var(--container-border-radius)] bg-black @container/media-root',
      'font-media text-media leading-normal subpixel-antialiased',
      'outline-2 -outline-offset-4 outline-transparent [transition-property:outline-offset,outline-color] [transition-duration:100ms] [transition-timing-function:ease-out]',
      'focus-visible:outline-current focus-visible:outline-offset-2',
      '[&_video]:block [&_video]:h-full [&_video]:w-full [&_video]:rounded-[inherit]',
      '[&_video]:[object-fit:var(--media-object-fit,contain)]',
      '[&_video]:[object-position:var(--media-object-position,center)]',
      'before:pointer-events-none before:absolute before:inset-0',
      'before:[background-image:var(--media-poster-placeholder,none)] before:bg-no-repeat',
      'before:[background-position:var(--media-object-position,center)]',
      'before:[background-size:var(--media-object-fit,contain)]',
      'before:opacity-0 before:[filter:blur(var(--media-poster-placeholder-blur,20px))]',
      'before:transition-opacity before:duration-250',
      'has-[img[data-visible]:not([data-loaded])]:before:opacity-100',
      'after:pointer-events-none after:absolute after:inset-0 after:z-10 after:rounded-[inherit]',
      'after:shadow-[inset_0_0_0_1px_var(--media-surface-border)] [&:fullscreen]:after:hidden',
      '[&:fullscreen]:[--container-border-radius:0] [&:fullscreen_video]:object-contain',
      'min-[1280px]:[&:fullscreen]:[--scale:1.25] min-[1536px]:[&:fullscreen]:[--scale:1.5]',
      'min-[1920px]:[&:fullscreen]:[--scale:1.75]',
      '[--media-caption-track-y:-0.5rem] [--media-caption-track-delay:25ms]',
      '[--media-caption-track-duration:var(--controls-transition-duration)]',
      'has-[[data-controls][data-visible]]:[--media-caption-track-y:-3.5rem]',
      '[&_video::-webkit-media-text-track-container]:translate-y-(--media-caption-track-y)',
      '[&_video::-webkit-media-text-track-container]:[transition-property:translate]',
      '[&_video::-webkit-media-text-track-container]:[transition-duration:var(--media-caption-track-duration)]',
      '[&_video::-webkit-media-text-track-container]:delay-(--media-caption-track-delay)',
    ],
  },
});
