/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Text } from '../text';

const prefix = 'airplay.';

/** @internal */
export const startText = {
  key: `${prefix}start`,
  text: 'Start AirPlay',
} as const satisfies Text;

/** @internal */
export const stopText = {
  key: `${prefix}stop`,
  text: 'Stop AirPlay',
} as const satisfies Text;
