/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'buttons.';

export const playText = {
  key: `${prefix}play`,
  text: 'Play',
} as const satisfies Text;

export const pauseText = {
  key: `${prefix}pause`,
  text: 'Pause',
} as const satisfies Text;

export const replayText = {
  key: `${prefix}replay`,
  text: 'Replay',
} as const satisfies Text;

export const muteText = {
  key: `${prefix}mute`,
  text: 'Mute',
} as const satisfies Text;

export const unmuteText = {
  key: `${prefix}unmute`,
  text: 'Unmute',
} as const satisfies Text;
