/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Text } from '../text';

const prefix = 'captions.';

/** @internal */
export const enableText = {
  key: `${prefix}enable`,
  text: 'Enable captions',
} as const satisfies Text;

/** @internal */
export const disableText = {
  key: `${prefix}disable`,
  text: 'Disable captions',
} as const satisfies Text;
