/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Text } from '../text';

const prefix = 'common.';

/** @internal */
export const emptyText = {
  key: `${prefix}empty`,
  text: '',
} as const satisfies Text;

/** @internal */
export const okText = {
  key: `${prefix}ok`,
  text: 'OK',
} as const satisfies Text;
