/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'container.';

export const labelText = {
  key: `${prefix}label`,
  text: 'Media player',
} as const satisfies Text;
