/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'errors.';

export const abortedText = {
  key: `${prefix}aborted`,
  text: 'You stopped media playback before it finished.',
} as const satisfies Text;

export const networkText = {
  key: `${prefix}network`,
  text: 'This media could not be loaded due to a network or server issue.',
} as const satisfies Text;

export const decodeText = {
  key: `${prefix}decode`,
  text: 'This media could not be played. It may be corrupted, or your browser may not support its format.',
} as const satisfies Text;

export const sourceText = {
  key: `${prefix}source`,
  text: 'This media could not be loaded. It may be unavailable, or your browser may not support its format.',
} as const satisfies Text;

export const encryptedText = {
  key: `${prefix}encrypted`,
  text: 'This media could not be played because it could not be decrypted.',
} as const satisfies Text;

export const titleText = {
  key: `${prefix}title`,
  text: 'Something went wrong.',
} as const satisfies Text;

export const unexpectedText = {
  key: `${prefix}unexpected`,
  text: 'An unexpected error occurred.',
} as const satisfies Text;
