/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Text } from '../text';

const prefix = 'fullscreen.';

/** @internal */
export const enterText = {
  key: `${prefix}enter`,
  text: 'Enter fullscreen',
} as const satisfies Text;

/** @internal */
export const exitText = {
  key: `${prefix}exit`,
  text: 'Exit fullscreen',
} as const satisfies Text;
