/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Text } from '../text';

const prefix = 'live.';

/** @internal */
export const playingText = {
  key: `${prefix}playing`,
  text: 'Playing live',
} as const satisfies Text;

/** @internal */
export const seekToEdgeText = {
  key: `${prefix}seekToEdge`,
  text: 'Seek to live edge',
} as const satisfies Text;

/** @internal */
export const badgeText = {
  key: `${prefix}badge`,
  text: 'Live',
} as const satisfies Text;
