/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'menu.';

export const settingsText = {
  key: `${prefix}settings`,
  text: 'Settings',
} as const satisfies Text;

export const qualityText = {
  key: `${prefix}quality`,
  text: 'Quality',
} as const satisfies Text;

export const audioText = {
  key: `${prefix}audio`,
  text: 'Audio',
} as const satisfies Text;

export const defaultText = {
  key: `${prefix}default`,
  text: 'Default',
} as const satisfies Text;

export const speedText = {
  key: `${prefix}speed`,
  text: 'Speed',
} as const satisfies Text;

export const captionsText = {
  key: `${prefix}captions`,
  text: 'Captions',
} as const satisfies Text;

export const playbackRateText = {
  key: `${prefix}playbackRate`,
  text: 'Playback rate',
} as const satisfies Text;

export const backText = {
  key: `${prefix}back`,
  text: 'Back',
} as const satisfies Text;

export const offText = {
  key: `${prefix}off`,
  text: 'Off',
} as const satisfies Text;

export const autoText = {
  key: `${prefix}auto`,
  text: 'Auto',
} as const satisfies Text;

export const autoWithLabelText = {
  key: `${prefix}autoWithLabel`,
  text: 'Auto ({label})',
} as const satisfies Text;

export const subtitlesText = {
  key: `${prefix}subtitles`,
  text: 'Subtitles',
} as const satisfies Text;
