/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'playback.';

export const rateText = {
  key: `${prefix}rate`,
  text: 'Playback rate {rate}',
} as const satisfies Text;
