/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'status.';

export const captionsOnText = {
  key: `${prefix}captionsOn`,
  text: 'Captions on',
} as const satisfies Text;

export const captionsOffText = {
  key: `${prefix}captionsOff`,
  text: 'Captions off',
} as const satisfies Text;

export const pausedText = {
  key: `${prefix}paused`,
  text: 'Paused',
} as const satisfies Text;

export const playingText = {
  key: `${prefix}playing`,
  text: 'Playing',
} as const satisfies Text;

export const fullscreenText = {
  key: `${prefix}fullscreen`,
  text: 'Fullscreen',
} as const satisfies Text;

export const pipText = {
  key: `${prefix}pip`,
  text: 'Picture in picture',
} as const satisfies Text;

export const exitPipText = {
  key: `${prefix}exitPip`,
  text: 'Exit picture in picture',
} as const satisfies Text;
