/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'time.';

export const currentText = {
  key: `${prefix}current`,
  text: 'Current time',
} as const satisfies Text;

export const durationText = {
  key: `${prefix}duration`,
  text: 'Duration',
} as const satisfies Text;

export const remainingText = {
  key: `${prefix}remaining`,
  text: 'Remaining',
} as const satisfies Text;

export const remainingSuffixText = {
  key: `${prefix}remainingSuffix`,
  text: '{duration} remaining',
} as const satisfies Text;

export const showElapsedText = {
  key: `${prefix}showElapsed`,
  text: '{duration}. Show elapsed time.',
} as const satisfies Text;

export const showDurationText = {
  key: `${prefix}showDuration`,
  text: '{duration}. Show duration.',
} as const satisfies Text;

export const showRemainingText = {
  key: `${prefix}showRemaining`,
  text: '{duration}. Show remaining time.',
} as const satisfies Text;

export const positionText = {
  key: `${prefix}position`,
  text: '{current} of {duration}',
} as const satisfies Text;
