/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'volume.';

export const mutedValueText = {
  key: `${prefix}mutedValue`,
  text: '{percent}, muted',
} as const satisfies Text;

export const mutedText = {
  key: `${prefix}muted`,
  text: 'Muted',
} as const satisfies Text;

export const labelText = {
  key: `${prefix}label`,
  text: 'Volume',
} as const satisfies Text;

export const valueText = {
  key: `${prefix}value`,
  text: 'Volume {value}',
} as const satisfies Text;
