export {
  DEFAULT_REGISTRY_PRESET,
  defaultRegistryStyling,
  defaultRegistryTemplate,
  REGISTRY_INSTALL_DIRECTORY,
  REGISTRY_NAMESPACE,
  REGISTRY_ORIGIN,
  REGISTRY_PRESETS,
  REGISTRY_SKINS,
  REGISTRY_STYLING_LABELS,
  REGISTRY_STYLINGS,
  REGISTRY_TEMPLATE_LABELS,
  REGISTRY_TEMPLATES,
  REGISTRY_THEME_LABELS,
  REGISTRY_THEMES,
  registryInstallCommands,
  registryNamespaceUrl,
  registrySkinSelection,
  registryStylings,
  registryTemplates,
  resolveRegistryStyling,
  resolveRegistryTemplate,
  SHADCN_RUNNER_NAMES,
  SHADCN_RUNNERS,
  shadcnAddCommand,
  shadcnCommand,
  shadcnInitCommand,
  shadcnRegistryAddCommand,
  type RegistryFramework,
  type RegistryPreset,
  type RegistryProjectFramework,
  type RegistrySkin,
  type RegistryStyling,
  type RegistryTemplate,
  type RegistryTheme,
  type ShadcnRunner,
} from '@videojs/installation';
