export {
  getInstallationPreset,
  getMediaSubpath,
  INSTALLATION_PRESETS,
  INSTALLATION_SKIN_FLAGS,
  isMuxRenderer,
  MUX_DATA_EXTENSION_SUBPATH,
  MUX_DATA_PACKAGE,
  RENDERERS,
  USE_CASES,
  type InstallationPreset,
  type InstallMethod,
  type Renderer,
  type Skin,
  type UseCase,
} from '@videojs/installation';
