// Generated by `vjsc generate`.
import { defineElement } from 'vjsc/components';

export const AirPlayButton = defineElement('media-airplay-button', {
  import: {
    from: '@videojs/html/ui/airplay-button',
    sideEffect: true,
  },
});

export const AlertDialog = defineElement('media-alert-dialog', {
  import: {
    from: '@videojs/html/ui/alert-dialog',
    sideEffect: true,
  },
});

export const AlertDialogClose = defineElement('media-alert-dialog-close', {
  import: {
    from: '@videojs/html/ui/alert-dialog-close',
    sideEffect: true,
  },
});

export const AlertDialogDescription = defineElement('media-alert-dialog-description', {
  import: {
    from: '@videojs/html/ui/alert-dialog-description',
    sideEffect: true,
  },
});

export const AlertDialogTitle = defineElement('media-alert-dialog-title', {
  import: {
    from: '@videojs/html/ui/alert-dialog-title',
    sideEffect: true,
  },
});

export const AudioTrackRadioGroup = defineElement('media-audio-track-radio-group', {
  import: {
    from: '@videojs/html/ui/audio-track-radio-group',
    sideEffect: true,
  },
});

export const BackgroundVideo = defineElement('background-video', {
  import: {
    from: '@videojs/html/media/background-video',
    sideEffect: true,
  },
});

export const BufferingIndicator = defineElement('media-buffering-indicator', {
  import: {
    from: '@videojs/html/ui/buffering-indicator',
    sideEffect: true,
  },
});

export const CaptionsButton = defineElement('media-captions-button', {
  import: {
    from: '@videojs/html/ui/captions-button',
    sideEffect: true,
  },
});

export const CaptionsRadioGroup = defineElement('media-captions-radio-group', {
  import: {
    from: '@videojs/html/ui/captions-radio-group',
    sideEffect: true,
  },
});

export const CastButton = defineElement('media-cast-button', {
  import: {
    from: '@videojs/html/ui/cast-button',
    sideEffect: true,
  },
});

export const Controls = defineElement('media-controls', {
  import: {
    from: '@videojs/html/ui/controls',
    sideEffect: true,
  },
});

export const ControlsGroup = defineElement('media-controls-group', {
  import: {
    from: '@videojs/html/ui/controls-group',
    sideEffect: true,
  },
});

export const DashVideo = defineElement('dash-video', {
  import: {
    from: '@videojs/html/media/dash-video',
    sideEffect: true,
  },
});

export const ErrorDialog = defineElement('media-error-dialog', {
  import: {
    from: '@videojs/html/ui/error-dialog',
    sideEffect: true,
  },
});

export const FullscreenButton = defineElement('media-fullscreen-button', {
  import: {
    from: '@videojs/html/ui/fullscreen-button',
    sideEffect: true,
  },
});

export const Gesture = defineElement('media-gesture', {
  import: {
    from: '@videojs/html/ui/gesture',
    sideEffect: true,
  },
});

export const HlsAudio = defineElement('hls-audio', {
  import: {
    from: '@videojs/html/media/hls-audio',
    sideEffect: true,
  },
});

export const HlsBackgroundVideo = defineElement('hls-background-video', {
  import: {
    from: '@videojs/html/media/hls-background-video',
    sideEffect: true,
  },
});

export const HlsJsVideo = defineElement('hlsjs-video', {
  import: {
    from: '@videojs/html/media/hlsjs-video',
    sideEffect: true,
  },
});

export const HlsVideo = defineElement('hls-video', {
  import: {
    from: '@videojs/html/media/hls-video',
    sideEffect: true,
  },
});

export const Hotkey = defineElement('media-hotkey', {
  import: {
    from: '@videojs/html/ui/hotkey',
    sideEffect: true,
  },
});

export const I18nProvider = defineElement('media-i18n', {
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
});

export const MediaContainer = defineElement('media-container', {
  import: {
    from: '@videojs/html/media/container',
    sideEffect: true,
  },
});

export const Menu = defineElement('media-menu', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuCheckboxItem = defineElement('media-menu-checkbox-item', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuGroup = defineElement('media-menu-group', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuGroupLabel = defineElement('media-menu-group-label', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuItem = defineElement('media-menu-item', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuItemIndicator = defineElement('media-menu-item-indicator', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuRadioGroup = defineElement('media-menu-radio-group', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuRadioItem = defineElement('media-menu-radio-item', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MenuSeparator = defineElement('media-menu-separator', {
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
});

export const MuteButton = defineElement('media-mute-button', {
  import: {
    from: '@videojs/html/ui/mute-button',
    sideEffect: true,
  },
});

export const MuxBackgroundVideo = defineElement('mux-background-video', {
  import: {
    from: '@videojs/html/media/mux-background-video',
    sideEffect: true,
  },
});

export const NativeHlsVideo = defineElement('native-hls-video', {
  import: {
    from: '@videojs/html/media/native-hls-video',
    sideEffect: true,
  },
});

export const PiPButton = defineElement('media-pip-button', {
  import: {
    from: '@videojs/html/ui/pip-button',
    sideEffect: true,
  },
});

export const PlaybackRateButton = defineElement('media-playback-rate-button', {
  import: {
    from: '@videojs/html/ui/playback-rate-button',
    sideEffect: true,
  },
});

export const PlaybackRateRadioGroup = defineElement('media-playback-rate-radio-group', {
  import: {
    from: '@videojs/html/ui/playback-rate-radio-group',
    sideEffect: true,
  },
});

export const PlayButton = defineElement('media-play-button', {
  import: {
    from: '@videojs/html/ui/play-button',
    sideEffect: true,
  },
});

export const Popover = defineElement('media-popover', {
  import: {
    from: '@videojs/html/ui/popover',
    sideEffect: true,
  },
});

export const Poster = defineElement('media-poster', {
  import: {
    from: '@videojs/html/ui/poster',
    sideEffect: true,
  },
});

export const QualityRadioGroup = defineElement('media-quality-radio-group', {
  import: {
    from: '@videojs/html/ui/quality-radio-group',
    sideEffect: true,
  },
});

export const SeekButton = defineElement('media-seek-button', {
  import: {
    from: '@videojs/html/ui/seek-button',
    sideEffect: true,
  },
});

export const SeekIndicator = defineElement('media-seek-indicator', {
  import: {
    from: '@videojs/html/ui/seek-indicator',
    sideEffect: true,
  },
});

export const SeekIndicatorValue = defineElement('media-seek-indicator-value', {
  import: {
    from: '@videojs/html/ui/seek-indicator-value',
    sideEffect: true,
  },
});

export const Slider = defineElement('media-slider', {
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
});

export const SliderBuffer = defineElement('media-slider-buffer', {
  import: {
    from: '@videojs/html/ui/slider-buffer',
    sideEffect: true,
  },
});

export const SliderFill = defineElement('media-slider-fill', {
  import: {
    from: '@videojs/html/ui/slider-fill',
    sideEffect: true,
  },
});

export const SliderPreview = defineElement('media-slider-preview', {
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
});

export const SliderThumb = defineElement('media-slider-thumb', {
  import: {
    from: '@videojs/html/ui/slider-thumb',
    sideEffect: true,
  },
});

export const SliderThumbnail = defineElement('media-slider-thumbnail', {
  import: {
    from: '@videojs/html/ui/slider-thumbnail',
    sideEffect: true,
  },
});

export const SliderTrack = defineElement('media-slider-track', {
  import: {
    from: '@videojs/html/ui/slider-track',
    sideEffect: true,
  },
});

export const SliderValue = defineElement('media-slider-value', {
  import: {
    from: '@videojs/html/ui/slider-value',
    sideEffect: true,
  },
});

export const StatusAnnouncer = defineElement('media-status-announcer', {
  import: {
    from: '@videojs/html/ui/status-announcer',
    sideEffect: true,
  },
});

export const StatusIndicator = defineElement('media-status-indicator', {
  import: {
    from: '@videojs/html/ui/status-indicator',
    sideEffect: true,
  },
});

export const StatusIndicatorValue = defineElement('media-status-indicator-value', {
  import: {
    from: '@videojs/html/ui/status-indicator-value',
    sideEffect: true,
  },
});

export const Text = defineElement('media-text', {
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
});

export const Thumbnail = defineElement('media-thumbnail', {
  import: {
    from: '@videojs/html/ui/thumbnail',
    sideEffect: true,
  },
});

export const Time = defineElement('media-time', {
  import: {
    from: '@videojs/html/ui/time',
    sideEffect: true,
  },
});

export const TimeGroup = defineElement('media-time-group', {
  import: {
    from: '@videojs/html/ui/time-group',
    sideEffect: true,
  },
});

export const TimeSeparator = defineElement('media-time-separator', {
  import: {
    from: '@videojs/html/ui/time-separator',
    sideEffect: true,
  },
});

export const TimeSlider = defineElement('media-time-slider', {
  import: {
    from: '@videojs/html/ui/time-slider',
    sideEffect: true,
  },
});

export const TimeSliderChapters = defineElement('media-time-slider-chapters', {
  import: {
    from: '@videojs/html/ui/time-slider-chapters',
    sideEffect: true,
  },
});

export const TimeSliderChapterTitle = defineElement('media-time-slider-chapter-title', {
  import: {
    from: '@videojs/html/ui/time-slider-chapter-title',
    sideEffect: true,
  },
});

export const Tooltip = defineElement('media-tooltip', {
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const TooltipGroup = defineElement('media-tooltip-group', {
  import: {
    from: '@videojs/html/ui/tooltip-group',
    sideEffect: true,
  },
});

export const TooltipLabel = defineElement('media-tooltip-label', {
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const TooltipShortcut = defineElement('media-tooltip-shortcut', {
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
});

export const VimeoVideo = defineElement('vimeo-video', {
  import: {
    from: '@videojs/html/media/vimeo-video',
    sideEffect: true,
  },
});

export const VolumeIndicator = defineElement('media-volume-indicator', {
  import: {
    from: '@videojs/html/ui/volume-indicator',
    sideEffect: true,
  },
});

export const VolumeIndicatorFill = defineElement('media-volume-indicator-fill', {
  import: {
    from: '@videojs/html/ui/volume-indicator-fill',
    sideEffect: true,
  },
});

export const VolumeIndicatorValue = defineElement('media-volume-indicator-value', {
  import: {
    from: '@videojs/html/ui/volume-indicator-value',
    sideEffect: true,
  },
});

export const VolumeSlider = defineElement('media-volume-slider', {
  import: {
    from: '@videojs/html/ui/volume-slider',
    sideEffect: true,
  },
});

export const YouTubeVideo = defineElement('youtube-video', {
  import: {
    from: '@videojs/html/media/youtube-video',
    sideEffect: true,
  },
});

export const targets = {
  AirPlayButton,
  AlertDialog,
  AlertDialogClose,
  AlertDialogDescription,
  AlertDialogTitle,
  AudioTrackRadioGroup,
  BackgroundVideo,
  BufferingIndicator,
  CaptionsButton,
  CaptionsRadioGroup,
  CastButton,
  Controls,
  ControlsGroup,
  DashVideo,
  ErrorDialog,
  FullscreenButton,
  Gesture,
  HlsAudio,
  HlsBackgroundVideo,
  HlsJsVideo,
  HlsVideo,
  Hotkey,
  I18nProvider,
  MediaContainer,
  Menu,
  MenuCheckboxItem,
  MenuGroup,
  MenuGroupLabel,
  MenuItem,
  MenuItemIndicator,
  MenuRadioGroup,
  MenuRadioItem,
  MenuSeparator,
  MuteButton,
  MuxBackgroundVideo,
  NativeHlsVideo,
  PiPButton,
  PlaybackRateButton,
  PlaybackRateRadioGroup,
  PlayButton,
  Popover,
  Poster,
  QualityRadioGroup,
  SeekButton,
  SeekIndicator,
  SeekIndicatorValue,
  Slider,
  SliderBuffer,
  SliderFill,
  SliderPreview,
  SliderThumb,
  SliderThumbnail,
  SliderTrack,
  SliderValue,
  StatusAnnouncer,
  StatusIndicator,
  StatusIndicatorValue,
  Text,
  Thumbnail,
  Time,
  TimeGroup,
  TimeSeparator,
  TimeSlider,
  TimeSliderChapters,
  TimeSliderChapterTitle,
  Tooltip,
  TooltipGroup,
  TooltipLabel,
  TooltipShortcut,
  VimeoVideo,
  VolumeIndicator,
  VolumeIndicatorFill,
  VolumeIndicatorValue,
  VolumeSlider,
  YouTubeVideo,
} as const;
