// Generated by `vjsc generate`.
export const AirPlayButton = {
  tagName: 'media-airplay-button',
  import: {
    from: '@videojs/html/ui/airplay-button',
    sideEffect: true,
  },
} as const;

export const AlertDialog = {
  tagName: 'media-alert-dialog',
  import: {
    from: '@videojs/html/ui/alert-dialog',
    sideEffect: true,
  },
} as const;

export const AlertDialogClose = {
  tagName: 'media-alert-dialog-close',
  import: {
    from: '@videojs/html/ui/alert-dialog-close',
    sideEffect: true,
  },
} as const;

export const AlertDialogDescription = {
  tagName: 'media-alert-dialog-description',
  import: {
    from: '@videojs/html/ui/alert-dialog-description',
    sideEffect: true,
  },
} as const;

export const AlertDialogTitle = {
  tagName: 'media-alert-dialog-title',
  import: {
    from: '@videojs/html/ui/alert-dialog-title',
    sideEffect: true,
  },
} as const;

export const AudioTrackRadioGroup = {
  tagName: 'media-audio-track-radio-group',
  import: {
    from: '@videojs/html/ui/audio-track-radio-group',
    sideEffect: true,
  },
} as const;

export const BackgroundVideo = {
  tagName: 'background-video',
  import: {
    from: '@videojs/html/media/background-video',
    sideEffect: true,
  },
} as const;

export const BufferingIndicator = {
  tagName: 'media-buffering-indicator',
  import: {
    from: '@videojs/html/ui/buffering-indicator',
    sideEffect: true,
  },
} as const;

export const CaptionsButton = {
  tagName: 'media-captions-button',
  import: {
    from: '@videojs/html/ui/captions-button',
    sideEffect: true,
  },
} as const;

export const CaptionsRadioGroup = {
  tagName: 'media-captions-radio-group',
  import: {
    from: '@videojs/html/ui/captions-radio-group',
    sideEffect: true,
  },
} as const;

export const CastButton = {
  tagName: 'media-cast-button',
  import: {
    from: '@videojs/html/ui/cast-button',
    sideEffect: true,
  },
} as const;

export const CloudflareVideo = {
  tagName: 'cloudflare-video',
  import: {
    from: '@videojs/html/media/cloudflare-video',
    sideEffect: true,
  },
} as const;

export const Controls = {
  tagName: 'media-controls',
  import: {
    from: '@videojs/html/ui/controls',
    sideEffect: true,
  },
} as const;

export const ControlsGroup = {
  tagName: 'media-controls-group',
  import: {
    from: '@videojs/html/ui/controls-group',
    sideEffect: true,
  },
} as const;

export const DashVideo = {
  tagName: 'dash-video',
  import: {
    from: '@videojs/html/media/dash-video',
    sideEffect: true,
  },
} as const;

export const ErrorDialog = {
  tagName: 'media-error-dialog',
  import: {
    from: '@videojs/html/ui/error-dialog',
    sideEffect: true,
  },
} as const;

export const FullscreenButton = {
  tagName: 'media-fullscreen-button',
  import: {
    from: '@videojs/html/ui/fullscreen-button',
    sideEffect: true,
  },
} as const;

export const Gesture = {
  tagName: 'media-gesture',
  import: {
    from: '@videojs/html/ui/gesture',
    sideEffect: true,
  },
} as const;

export const HlsAudio = {
  tagName: 'hls-audio',
  import: {
    from: '@videojs/html/media/hls-audio',
    sideEffect: true,
  },
} as const;

export const HlsBackgroundVideo = {
  tagName: 'hls-background-video',
  import: {
    from: '@videojs/html/media/hls-background-video',
    sideEffect: true,
  },
} as const;

export const HlsJsVideo = {
  tagName: 'hlsjs-video',
  import: {
    from: '@videojs/html/media/hlsjs-video',
    sideEffect: true,
  },
} as const;

export const HlsVideo = {
  tagName: 'hls-video',
  import: {
    from: '@videojs/html/media/hls-video',
    sideEffect: true,
  },
} as const;

export const Hotkey = {
  tagName: 'media-hotkey',
  import: {
    from: '@videojs/html/ui/hotkey',
    sideEffect: true,
  },
} as const;

export const I18nProvider = {
  tagName: 'media-i18n',
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
} as const;

export const MediaContainer = {
  tagName: 'media-container',
  import: {
    from: '@videojs/html/media/container',
    sideEffect: true,
  },
} as const;

export const Menu = {
  tagName: 'media-menu',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuCheckboxItem = {
  tagName: 'media-menu-checkbox-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuGroup = {
  tagName: 'media-menu-group',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuGroupLabel = {
  tagName: 'media-menu-group-label',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuItem = {
  tagName: 'media-menu-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuItemIndicator = {
  tagName: 'media-menu-item-indicator',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuRadioGroup = {
  tagName: 'media-menu-radio-group',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuRadioItem = {
  tagName: 'media-menu-radio-item',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MenuSeparator = {
  tagName: 'media-menu-separator',
  import: {
    from: '@videojs/html/ui/menu',
    sideEffect: true,
  },
} as const;

export const MuteButton = {
  tagName: 'media-mute-button',
  import: {
    from: '@videojs/html/ui/mute-button',
    sideEffect: true,
  },
} as const;

export const MuxBackgroundVideo = {
  tagName: 'mux-background-video',
  import: {
    from: '@videojs/html/media/mux-background-video',
    sideEffect: true,
  },
} as const;

export const NativeHlsVideo = {
  tagName: 'native-hls-video',
  import: {
    from: '@videojs/html/media/native-hls-video',
    sideEffect: true,
  },
} as const;

export const PiPButton = {
  tagName: 'media-pip-button',
  import: {
    from: '@videojs/html/ui/pip-button',
    sideEffect: true,
  },
} as const;

export const PlaybackRateButton = {
  tagName: 'media-playback-rate-button',
  import: {
    from: '@videojs/html/ui/playback-rate-button',
    sideEffect: true,
  },
} as const;

export const PlaybackRateRadioGroup = {
  tagName: 'media-playback-rate-radio-group',
  import: {
    from: '@videojs/html/ui/playback-rate-radio-group',
    sideEffect: true,
  },
} as const;

export const PlayButton = {
  tagName: 'media-play-button',
  import: {
    from: '@videojs/html/ui/play-button',
    sideEffect: true,
  },
} as const;

export const Popover = {
  tagName: 'media-popover',
  import: {
    from: '@videojs/html/ui/popover',
    sideEffect: true,
  },
} as const;

export const Poster = {
  tagName: 'media-poster',
  import: {
    from: '@videojs/html/ui/poster',
    sideEffect: true,
  },
} as const;

export const QualityRadioGroup = {
  tagName: 'media-quality-radio-group',
  import: {
    from: '@videojs/html/ui/quality-radio-group',
    sideEffect: true,
  },
} as const;

export const SeekButton = {
  tagName: 'media-seek-button',
  import: {
    from: '@videojs/html/ui/seek-button',
    sideEffect: true,
  },
} as const;

export const SeekIndicator = {
  tagName: 'media-seek-indicator',
  import: {
    from: '@videojs/html/ui/seek-indicator',
    sideEffect: true,
  },
} as const;

export const SeekIndicatorValue = {
  tagName: 'media-seek-indicator-value',
  import: {
    from: '@videojs/html/ui/seek-indicator-value',
    sideEffect: true,
  },
} as const;

export const Slider = {
  tagName: 'media-slider',
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
} as const;

export const SliderBuffer = {
  tagName: 'media-slider-buffer',
  import: {
    from: '@videojs/html/ui/slider-buffer',
    sideEffect: true,
  },
} as const;

export const SliderFill = {
  tagName: 'media-slider-fill',
  import: {
    from: '@videojs/html/ui/slider-fill',
    sideEffect: true,
  },
} as const;

export const SliderPreview = {
  tagName: 'media-slider-preview',
  import: {
    from: '@videojs/html/ui/slider',
    sideEffect: true,
  },
} as const;

export const SliderThumb = {
  tagName: 'media-slider-thumb',
  import: {
    from: '@videojs/html/ui/slider-thumb',
    sideEffect: true,
  },
} as const;

export const SliderThumbnail = {
  tagName: 'media-slider-thumbnail',
  import: {
    from: '@videojs/html/ui/slider-thumbnail',
    sideEffect: true,
  },
} as const;

export const SliderTrack = {
  tagName: 'media-slider-track',
  import: {
    from: '@videojs/html/ui/slider-track',
    sideEffect: true,
  },
} as const;

export const SliderValue = {
  tagName: 'media-slider-value',
  import: {
    from: '@videojs/html/ui/slider-value',
    sideEffect: true,
  },
} as const;

export const SpotifyAudio = {
  tagName: 'spotify-audio',
  import: {
    from: '@videojs/html/media/spotify-audio',
    sideEffect: true,
  },
} as const;

export const StatusAnnouncer = {
  tagName: 'media-status-announcer',
  import: {
    from: '@videojs/html/ui/status-announcer',
    sideEffect: true,
  },
} as const;

export const StatusIndicator = {
  tagName: 'media-status-indicator',
  import: {
    from: '@videojs/html/ui/status-indicator',
    sideEffect: true,
  },
} as const;

export const StatusIndicatorValue = {
  tagName: 'media-status-indicator-value',
  import: {
    from: '@videojs/html/ui/status-indicator-value',
    sideEffect: true,
  },
} as const;

export const Text = {
  tagName: 'media-text',
  import: {
    from: '@videojs/html/i18n',
    sideEffect: true,
  },
} as const;

export const Thumbnail = {
  tagName: 'media-thumbnail',
  import: {
    from: '@videojs/html/ui/thumbnail',
    sideEffect: true,
  },
} as const;

export const TikTokVideo = {
  tagName: 'tiktok-video',
  import: {
    from: '@videojs/html/media/tiktok-video',
    sideEffect: true,
  },
} as const;

export const Time = {
  tagName: 'media-time',
  import: {
    from: '@videojs/html/ui/time',
    sideEffect: true,
  },
} as const;

export const TimeGroup = {
  tagName: 'media-time-group',
  import: {
    from: '@videojs/html/ui/time-group',
    sideEffect: true,
  },
} as const;

export const TimeSeparator = {
  tagName: 'media-time-separator',
  import: {
    from: '@videojs/html/ui/time-separator',
    sideEffect: true,
  },
} as const;

export const TimeSlider = {
  tagName: 'media-time-slider',
  import: {
    from: '@videojs/html/ui/time-slider',
    sideEffect: true,
  },
} as const;

export const TimeSliderChapters = {
  tagName: 'media-time-slider-chapters',
  import: {
    from: '@videojs/html/ui/time-slider-chapters',
    sideEffect: true,
  },
} as const;

export const TimeSliderChapterTitle = {
  tagName: 'media-time-slider-chapter-title',
  import: {
    from: '@videojs/html/ui/time-slider-chapter-title',
    sideEffect: true,
  },
} as const;

export const Tooltip = {
  tagName: 'media-tooltip',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
} as const;

export const TooltipGroup = {
  tagName: 'media-tooltip-group',
  import: {
    from: '@videojs/html/ui/tooltip-group',
    sideEffect: true,
  },
} as const;

export const TooltipLabel = {
  tagName: 'media-tooltip-label',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
} as const;

export const TooltipShortcut = {
  tagName: 'media-tooltip-shortcut',
  import: {
    from: '@videojs/html/ui/tooltip',
    sideEffect: true,
  },
} as const;

export const TwitchVideo = {
  tagName: 'twitch-video',
  import: {
    from: '@videojs/html/media/twitch-video',
    sideEffect: true,
  },
} as const;

export const VimeoVideo = {
  tagName: 'vimeo-video',
  import: {
    from: '@videojs/html/media/vimeo-video',
    sideEffect: true,
  },
} as const;

export const VolumeIndicator = {
  tagName: 'media-volume-indicator',
  import: {
    from: '@videojs/html/ui/volume-indicator',
    sideEffect: true,
  },
} as const;

export const VolumeIndicatorFill = {
  tagName: 'media-volume-indicator-fill',
  import: {
    from: '@videojs/html/ui/volume-indicator-fill',
    sideEffect: true,
  },
} as const;

export const VolumeIndicatorValue = {
  tagName: 'media-volume-indicator-value',
  import: {
    from: '@videojs/html/ui/volume-indicator-value',
    sideEffect: true,
  },
} as const;

export const VolumeSlider = {
  tagName: 'media-volume-slider',
  import: {
    from: '@videojs/html/ui/volume-slider',
    sideEffect: true,
  },
} as const;

export const YouTubeVideo = {
  tagName: 'youtube-video',
  import: {
    from: '@videojs/html/media/youtube-video',
    sideEffect: true,
  },
} as const;

export const entries = {
  AirPlayButton,
  AlertDialog,
  AlertDialogClose,
  AlertDialogDescription,
  AlertDialogTitle,
  AudioTrackRadioGroup,
  BackgroundVideo,
  BufferingIndicator,
  CaptionsButton,
  CaptionsRadioGroup,
  CastButton,
  CloudflareVideo,
  Controls,
  ControlsGroup,
  DashVideo,
  ErrorDialog,
  FullscreenButton,
  Gesture,
  HlsAudio,
  HlsBackgroundVideo,
  HlsJsVideo,
  HlsVideo,
  Hotkey,
  I18nProvider,
  MediaContainer,
  Menu,
  MenuCheckboxItem,
  MenuGroup,
  MenuGroupLabel,
  MenuItem,
  MenuItemIndicator,
  MenuRadioGroup,
  MenuRadioItem,
  MenuSeparator,
  MuteButton,
  MuxBackgroundVideo,
  NativeHlsVideo,
  PiPButton,
  PlaybackRateButton,
  PlaybackRateRadioGroup,
  PlayButton,
  Popover,
  Poster,
  QualityRadioGroup,
  SeekButton,
  SeekIndicator,
  SeekIndicatorValue,
  Slider,
  SliderBuffer,
  SliderFill,
  SliderPreview,
  SliderThumb,
  SliderThumbnail,
  SliderTrack,
  SliderValue,
  SpotifyAudio,
  StatusAnnouncer,
  StatusIndicator,
  StatusIndicatorValue,
  Text,
  Thumbnail,
  TikTokVideo,
  Time,
  TimeGroup,
  TimeSeparator,
  TimeSlider,
  TimeSliderChapters,
  TimeSliderChapterTitle,
  Tooltip,
  TooltipGroup,
  TooltipLabel,
  TooltipShortcut,
  TwitchVideo,
  VimeoVideo,
  VolumeIndicator,
  VolumeIndicatorFill,
  VolumeIndicatorValue,
  VolumeSlider,
  YouTubeVideo,
} as const;
