/**
 * @fileoverview Auto-generated React component from SVG
 *
 * This file is automatically generated by SVGR from SVG files located in:
 * packages/icons/assets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * To modify this icon:
 * 1. Edit the corresponding SVG file in packages/icons/assets/
 * 2. Run `pnpm -F react generate:icons` in this package to regenerate components
 *
 * @generated
 */
import type { IconProps } from '../types';
const SvgFullscreenEnter = ({
  color = 'currentColor',
  ...props
}: IconProps): JSX.Element => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={18} viewBox="0 0 18 18" fill={color} aria-hidden="true" {...props}><path d="M9.57,3.617c-.156-.375-.519-.617-.924-.617H4c-.552,0-1,.449-1,1v4.646c0,.406,.242,.769,.618,.924,.124,.051,.255,.076,.383,.076,.261,0,.515-.102,.706-.293l4.647-4.647c.286-.287,.371-.715,.216-1.089Z" className="arrow-1" /><path d="M14.382,8.429c-.377-.156-.804-.068-1.089,.217l-4.647,4.647c-.286,.287-.371,.715-.216,1.089,.156,.375,.519,.617,.924,.617h4.646c.552,0,1-.449,1-1v-4.646c0-.406-.242-.769-.618-.924Z" className="arrow-2" /></svg>;
export default SvgFullscreenEnter;