/**
 * @fileoverview Auto-generated React component from SVG
 *
 * This file is automatically generated by SVGR from SVG files located in:
 * packages/icons/assets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * To modify this icon:
 * 1. Edit the corresponding SVG file in packages/icons/assets/
 * 2. Run `pnpm -F react generate:icons` in this package to regenerate components
 *
 * @generated
 */
import type { IconProps } from '../types';
const SvgFullscreenEnterAlt = ({
  color = 'currentColor',
  ...props
}: IconProps): JSX.Element => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={18} viewBox="0 0 18 18" fill={color} aria-hidden="true" {...props}><path d="M15.25 2h.017q.03 0 .06.004za.75.75 0 0 1 .599.298l-.069-.078a.75.75 0 0 1 .22.53v4.5a.75.75 0 1 1-1.5 0V4.56l-3.22 3.22a.75.75 0 0 1-1.06-1.06l3.218-3.22H10.75a.75.75 0 0 1-.743-.648L10 2.75a.75.75 0 0 1 .75-.75z" className="arrow-1" /><path d="M2.75 10a.75.75 0 0 1 .75.75v2.688l3.22-3.218a.75.75 0 0 1 1.06 1.06L4.56 14.5h2.69a.75.75 0 0 1 .743.648L8 15.25a.75.75 0 0 1-.75.75H2.722l-.046-.004.074.004a.75.75 0 0 1-.599-.298l.069.078a.75.75 0 0 1-.22-.53v-4.5a.75.75 0 0 1 .75-.75" className="arrow-2" /></svg>;
export default SvgFullscreenEnterAlt;