/**
 * @fileoverview Auto-generated index file for React icon components
 *
 * This file is automatically generated by SVGR from SVG files located in:
 * packages/icons/assets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * To modify icons or add new ones:
 * 1. Add/edit SVG files in packages/core/icons/assets/
 * 2. Run `pnpm -F react generate:icons` in this package to regenerate components
 *
 * @generated
 */
export { default as FullscreenEnterAltIcon } from "./FullscreenEnterAlt";
export { default as FullscreenEnterIcon } from "./FullscreenEnter";
export { default as FullscreenExitAltIcon } from "./FullscreenExitAlt";
export { default as FullscreenExitIcon } from "./FullscreenExit";
export { default as PauseIcon } from "./Pause";
export { default as PlayIcon } from "./Play";
export { default as SpinnerIcon } from "./Spinner";
export { default as VolumeHighIcon } from "./VolumeHigh";
export { default as VolumeLowIcon } from "./VolumeLow";
export { default as VolumeOffIcon } from "./VolumeOff";
