/**
 * @fileoverview Auto-generated React component from SVG
 *
 * This file is automatically generated by SVGR from SVG files located in:
 * packages/icons/assets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * To modify this icon:
 * 1. Edit the corresponding SVG file in packages/icons/assets/
 * 2. Run `pnpm -F react generate:icons` in this package to regenerate components
 *
 * @generated
 */
import type { IconProps } from '../types';
const SvgPause = ({
  color = 'currentColor',
  ...props
}: IconProps): JSX.Element => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={18} viewBox="0 0 18 18" fill={color} aria-hidden="true" {...props}><rect x={2} y={2} width={5} height={14} rx={1.75} ry={1.75} /><rect x={11} y={2} width={5} height={14} rx={1.75} ry={1.75} /></svg>;
export default SvgPause;