/**
 * @fileoverview Auto-generated React component from SVG
 *
 * This file is automatically generated by SVGR from SVG files located in:
 * packages/icons/assets/
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * To modify this icon:
 * 1. Edit the corresponding SVG file in packages/icons/assets/
 * 2. Run `pnpm -F react generate:icons` in this package to regenerate components
 *
 * @generated
 */
import type { IconProps } from '../types';
const SvgPlay = ({
  color = 'currentColor',
  ...props
}: IconProps): JSX.Element => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={18} viewBox="0 0 18 18" fill={color} aria-hidden="true" {...props}><path d="M15.1,7.478L5.608,2.222c-.553-.306-1.206-.297-1.749,.023-.538,.317-.859,.877-.859,1.499V14.256c0,.622,.321,1.182,.859,1.499,.279,.164,.586,.247,.895,.247,.293,0,.586-.075,.854-.223l9.491-5.256c.556-.307,.901-.891,.901-1.522s-.345-1.215-.9-1.522Z" /></svg>;
export default SvgPlay;