import { defineRule } from "@oxlint/plugins";

import type { ESTree, Fixer, SourceCode } from "@oxlint/plugins";

type Statement = ESTree.Directive | ESTree.Statement;

const CONTROL_FLOW_TYPES = new Set([
	"DoWhileStatement",
	"ForInStatement",
	"ForOfStatement",
	"ForStatement",
	"IfStatement",
	"SwitchStatement",
	"TryStatement",
	"WhileStatement",
]);

// Padding detection and comment anchoring follow the behavior of
// `@stylistic/padding-line-between-statements` (MIT).
// https://eslint.style/rules/default/padding-line-between-statements

function unwrapLabeledStatement(statement: Statement): Statement {
	while (statement.type === "LabeledStatement") statement = statement.body;

	return statement;
}

function isVariableDeclaration(statement: Statement): boolean {
	return unwrapLabeledStatement(statement).type === "VariableDeclaration";
}

function isControlFlowStatement(statement: Statement): boolean {
	return CONTROL_FLOW_TYPES.has(unwrapLabeledStatement(statement).type);
}

function requiresBlankLine(previous: Statement, current: Statement): boolean {
	if (isVariableDeclaration(previous) && isVariableDeclaration(current)) return false;

	return (
		isVariableDeclaration(previous) ||
		isControlFlowStatement(previous) ||
		isControlFlowStatement(current)
	);
}

function hasBlankLine(sourceCode: SourceCode, previous: Statement, current: Statement): boolean {
	const lastToken = sourceCode.getLastToken(previous);

	if (!lastToken) return true;

	let previousToken: ESTree.Comment | ESTree.Token = lastToken;

	while (previousToken.range[0] < current.range[0]) {
		const nextToken: ESTree.Comment | ESTree.Token | null = sourceCode.getTokenAfter(previousToken, {
			includeComments: true,
		});

		if (!nextToken) return true;

		if (nextToken.loc.start.line - previousToken.loc.end.line >= 2) return true;

		if (nextToken.range[0] >= current.range[0]) return false;

		previousToken = nextToken;
	}

	return false;
}

function insertBlankLine(
	sourceCode: SourceCode,
	previous: Statement,
	current: Statement,
	fixer: Fixer,
) {
	let previousToken: ESTree.Comment | ESTree.Token | null = sourceCode.getLastToken(previous);

	if (!previousToken) return null;

	const nextToken =
		sourceCode.getFirstTokenBetween(previousToken, current, {
			includeComments: true,
			filter(token) {
				if (previousToken && previousToken.loc.end.line === token.loc.start.line) {
					previousToken = token;

					return false;
				}

				return true;
			},
		}) ?? current;
	const newline = sourceCode.text.includes("\r\n") ? "\r\n" : "\n";
	const text = previousToken.loc.end.line === nextToken.loc.start.line ? `${newline}${newline}` : newline;

	return fixer.insertTextAfter(previousToken, text);
}

/** Keep declarations and control flow in distinct visual paragraphs. */
export const paddingLineBetweenStatementsRule = defineRule({
	meta: {
		type: "layout",
		docs: {
			description: "Require blank lines after declaration groups and around control-flow statements.",
		},
		fixable: "whitespace",
		messages: {
			expectedBlankLine: "Expected a blank line between these statements.",
		},
	},
	createOnce(context) {
		const inspectStatements = (statements: Statement[]) => {
			for (let index = 1; index < statements.length; index++) {
				const previous = statements[index - 1];
				const current = statements[index];

				if (!requiresBlankLine(previous, current) || hasBlankLine(context.sourceCode, previous, current)) {
					continue;
				}

				context.report({
					node: current,
					messageId: "expectedBlankLine",
					fix: (fixer) => insertBlankLine(context.sourceCode, previous, current, fixer),
				});
			}
		};

		return {
			before() {
				return !context.sourceCode.text.startsWith("/** Generated by ");
			},
			BlockStatement: (node) => inspectStatements(node.body),
			Program: (node) => inspectStatements(node.body),
			StaticBlock: (node) => inspectStatements(node.body),
			SwitchCase: (node) => inspectStatements(node.consequent),
			TSModuleBlock: (node) => inspectStatements(node.body),
		};
	},
});
