import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { describe, expect, it } from 'vite-plus/test';

import {
  createCandidateManifest,
  discoverStyleModules,
  parseCandidateManifest,
  renderCandidateManifest,
  resolveCandidateManifestPath,
} from '../candidates';
import type { ResolvedStyleRule } from '../resolved';

describe('renderCandidateManifest', () => {
  it('lists base and variant utilities once as Tailwind inline sources', () => {
    const button = { ...rule('media-button', ['grid', 'p-0']), variants: { compact: ['p-1', 'grid'] } };

    expect(renderCandidateManifest([button])).toBe(
      [
        '/* Generated by vjsc. Style module utilities for Tailwind source scanning. */',
        '@source inline("grid");',
        '@source inline("p-0");',
        '@source inline("p-1");',
        '',
      ].join('\n')
    );
  });

  it('carries extra candidates over', () => {
    expect(parseCandidateManifest(renderCandidateManifest([rule('media-button', ['grid'])], ['persisted']))).toEqual([
      'grid',
      'persisted',
    ]);
  });
});

describe('createCandidateManifest', () => {
  it('lands parallel records as one well-formed manifest', async () => {
    const path = join(await mkdtemp(join(tmpdir(), 'vjsc-manifest-')), 'vjsc/candidates.css');
    const manifest = createCandidateManifest(path);
    const utilities = Array.from({ length: 24 }, (_, index) => `p-${index}`);

    await manifest.ensure();
    await Promise.all(
      utilities.map((utility, index) =>
        manifest.record({
          modules: new Map([[`module-${index}`, new Map([['root', rule(`media-${index}`, [utility, 'grid'])]])]]),
        })
      )
    );

    const content = await readFile(path, 'utf8');
    const stray = content
      .split('\n')
      .filter((line) => line && !line.startsWith('/*') && !/^@source inline\(".*"\);$/.test(line));

    expect(stray).toEqual([]);
    expect(parseCandidateManifest(content)).toEqual(expect.arrayContaining([...utilities, 'grid']));
  });
});

describe('resolveCandidateManifestPath', () => {
  it('places the manifest in the owning package cache directory', () => {
    const packageDir = resolve(import.meta.dirname, '../../..');

    expect(resolveCandidateManifestPath(import.meta.dirname)).toBe(
      resolve(packageDir, 'node_modules/.vite/vjsc/candidates.css')
    );
    expect(resolveCandidateManifestPath(packageDir, '.cache')).toBe(resolve(packageDir, '.cache/vjsc/candidates.css'));
  });
});

describe('discoverStyleModules', () => {
  it('lists style modules matched by relative and absolute globs once', () => {
    const fixtures = resolve(import.meta.dirname, '../../plugins/tests/fixtures');
    const files = discoverStyleModules(fixtures, ['*.styles.ts', resolve(fixtures, 'title.styles.ts'), '*.css']);

    expect(files).toContain(resolve(fixtures, 'title.styles.ts'));
    expect(files.filter((file) => file.endsWith('title.styles.ts'))).toHaveLength(1);
    expect(files.every((file) => file.endsWith('.styles.ts'))).toBe(true);
  });
});

function rule(className: string, utilities: readonly string[]): ResolvedStyleRule {
  return {
    modulePath: '/fixture.styles.ts',
    tokenPath: ['root'],
    className,
    file: 'buttons.css',
    layer: 'components',
    scopeRoot: false,
    shadowHost: false,
    utilityGroups: utilities,
    utilities,
    variantGroups: {},
    variants: {},
  };
}
