name: Auto-label new issues

on:
  issues:
    types: [opened]

jobs:
  add-triage:
    if: github.event.issue.pull_request == null
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label triage
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
